; Auto-generated by icon_emit.c — Tiny-ICON Byrd Box x64
bits 64
default rel

section .bss
    icn_retval: resq 1
    icn_scan_oldsubj_3: resq 1
    icn_scan_oldpos_3: resq 1
    icn_find_s1_25: resq 1
    icn_find_s2_25: resq 1
    icn_find_pos_25: resq 1
    icn_cc26_lptr: resq 1
    icn_cc26_rptr: resq 1
    icn_failed: resb 1
    icn_suspended: resb 1
    icn_suspend_resume: resq 1
    icn_suspend_rbp: resq 1

section .text
    global _start
    extern icn_write_int
    extern icn_write_str
    extern icn_push
    extern icn_pop
    extern icn_str_concat
    extern icn_str_eq
    extern icn_any
    extern icn_many
    extern icn_upto
    extern icn_str_find
    extern icn_match
    extern icn_tab
    extern icn_move
    extern icn_subject
    extern icn_pos

_start:
    call    icn_main
    mov     rax, 60
    xor     rdi, rdi
    syscall


; === procedure main ===
    ; WHILE  id=0
    ; CALL read  id=2
icon_2_α:
    jmp     icn_main_done
icon_2_β:
    jmp     icn_main_done
icon_1_α:
    jmp     icon_2_α
icon_1_β:
    jmp     icon_2_β
icon_1_store:
    pop     rax
    mov     [rbp-8], rax
    jmp     icon_0_condok
icon_0_condok:
    add     rsp, 8
    ; VAR line  id=4
icon_4_α:
    mov     rax, [rbp-8]
    push    rax
    jmp     icon_3_scan_setup
icon_4_β:
    jmp     icon_0_top
    ; CALL write  id=6
    ; CALL meander  id=7
    ; VAR n  id=8
icon_8_α:
    mov     rax, [rbp-24]
    push    rax
    jmp     icon_7_push1
icon_8_β:
    jmp     icon_3_scan_bfail
icon_7_push1:
    pop     rdi
    call    icn_push
    jmp     icon_7_docall
    ; VAR alpha  id=9
icon_9_α:
    mov     rax, [rbp-16]
    push    rax
    jmp     icon_7_push0
icon_9_β:
    jmp     icon_3_scan_bfail
icon_7_push0:
    pop     rdi
    call    icn_push
    jmp     icon_8_α
icon_7_α:
    jmp     icon_9_α
icon_7_β:
    jmp     icon_3_scan_bfail
icon_7_docall:
    call    icn_meander
    movzx   rax, byte [rel icn_failed]
    test    rax, rax
    jnz     icon_3_scan_bfail
    mov     rax, [rel icn_retval]
    push    rax
    jmp     icon_6_call
icon_6_α:
    jmp     icon_7_α
icon_6_β:
    jmp     icon_7_β
icon_6_call:
    pop     rdi
    call    icn_write_int
    jmp     icon_3_scan_bok
    ; CALL stop  id=10
icon_10_α:
    jmp     icon_3_scan_bfail
icon_10_β:
    jmp     icon_3_scan_bfail
    ; CALL integer  id=13
icon_13_α:
    jmp     icon_5_else
icon_13_β:
    jmp     icon_5_else
icon_12_α:
    jmp     icon_13_α
icon_12_β:
    jmp     icon_13_β
icon_12_store:
    pop     rax
    jmp     icon_11_store
icon_11_α:
    jmp     icon_12_α
icon_11_β:
    jmp     icon_12_β
icon_11_store:
    pop     rax
    mov     [rbp-16], rax
    jmp     icon_5_then
icon_5_then:
    add     rsp, 8
    jmp     icon_6_α
icon_5_else:
    jmp     icon_10_α
icon_5_α:
    jmp     icon_11_α
icon_5_β:
    jmp     icon_11_β
    ; SCAN  id=3
icon_3_α:
    jmp     icon_4_α
icon_3_β:
    jmp     icon_3_scan_bret
icon_3_scan_setup:
    pop     rax
    push    rax
    mov     rcx, [rel icn_subject]
    mov     [rel icn_scan_oldsubj_3], rcx
    mov     rcx, [rel icn_pos]
    mov     [rel icn_scan_oldpos_3], rcx
    pop     rax
    mov     [rel icn_subject], rax
    mov     qword [rel icn_pos], 0
    jmp     icon_5_α
icon_3_scan_bok:
    mov     rax, [rel icn_scan_oldsubj_3]
    mov     [rel icn_subject], rax
    mov     rax, [rel icn_scan_oldpos_3]
    mov     [rel icn_pos], rax
    jmp     icon_0_top
icon_3_scan_bfail:
    mov     rax, [rel icn_scan_oldsubj_3]
    mov     [rel icn_subject], rax
    mov     rax, [rel icn_scan_oldpos_3]
    mov     [rel icn_pos], rax
    jmp     icon_4_β
icon_3_scan_bret:
    mov     rax, [rel icn_scan_oldsubj_3]
    mov     [rel icn_subject], rax
    mov     rax, [rel icn_scan_oldpos_3]
    mov     [rel icn_pos], rax
    jmp     icon_5_β
    jmp     icon_3_α
icon_0_top:
    jmp     icon_1_α
icon_0_α:
    jmp     icon_1_α
icon_0_β:
    jmp     icn_main_done
icn_main:
    push    rbp
    mov     rbp, rsp
    sub     rsp, 32
    jmp     icon_0_α
icn_main_done:
    mov     byte [rel icn_failed], 1
    add     rsp, 32
    pop     rbp
    ret

; === procedure meander ===
    ; VAR result  id=15
icon_15_α:
    mov     rax, [rbp-24]
    push    rax
    jmp     icon_14_ret_store
icon_15_β:
    jmp     icon_14_ret_store
icon_14_α:
    jmp     icon_15_α
icon_14_β:
    jmp     icn_meander_ret
icon_14_ret_store:
    pop     rax
    mov     [rel icn_retval], rax
    mov     byte [rel icn_failed], 0
    jmp     icn_meander_ret
    ; WHILE  id=16
    ; UNIMPL SUBSCRIPT id=18
icon_18_α:
    jmp     icon_14_α
icon_18_β:
    jmp     icon_14_α
icon_17_α:
    jmp     icon_18_α
icon_17_β:
    jmp     icon_18_β
icon_17_store:
    pop     rax
    mov     [rbp-48], rax
    jmp     icon_16_condok
icon_16_condok:
    add     rsp, 8
    ; SUB  id=21
    ; INT 1  id=22
icon_22_α:
    push    1
    jmp     icon_21_compute
icon_22_β:
    jmp     icon_21_lb
    ; VAR i  id=23
icon_23_α:
    mov     rax, [rbp-40]
    push    rax
    jmp     icon_21_lstore
icon_23_β:
    jmp     icon_16_top
icon_21_lb:
    jmp     icon_23_β
icon_21_α:
    mov     qword [rbp-72], 0
    jmp     icon_23_α
icon_21_β:
    mov     qword [rbp-72], 1
    jmp     icon_23_α
icon_21_lstore:
    pop     rax
    mov     [rbp-64], rax
    cmp     qword [rbp-72], 0
    je      icon_22_α
    jmp     icon_22_β
icon_21_compute:
    pop     rax
    mov     rcx, [rbp-64]
    sub     rcx, rax
    push    rcx
    jmp     icon_20_aug_store
icon_20_α:
    jmp     icon_21_α
icon_20_β:
    jmp     icon_21_β
icon_20_aug_store:
    pop     rax
    mov     [rbp-40], rax
    jmp     icon_16_top
    ; UNIMPL SEQ_EXPR id=24
icon_24_α:
    jmp     icon_16_top
icon_24_β:
    jmp     icon_16_top
    ; CALL find  id=25
    ; CONCAT  id=26
    ; VAR c  id=27
icon_27_α:
    mov     rax, [rbp-48]
    push    rax
    jmp     icon_26_rrelay
icon_27_β:
    jmp     icon_26_lb
    ; UNIMPL SECTION id=28
icon_28_α:
    jmp     icon_19_else
icon_28_β:
    jmp     icon_19_else
icon_26_lrelay:
    pop     rax
    mov     [rel icn_cc26_lptr], rax
    jmp     icon_26_lstore
icon_26_rrelay:
    pop     rax
    mov     [rel icn_cc26_rptr], rax
    jmp     icon_26_compute
icon_26_lb:
    jmp     icon_28_β
icon_26_α:
    mov     qword [rbp-80], 0
    jmp     icon_28_α
icon_26_β:
    jmp     icon_27_β
icon_26_lstore:
    cmp     qword [rbp-80], 0
    je      icon_27_α
    jmp     icon_27_β
icon_26_compute:
    mov     rdi, [rel icn_cc26_lptr]
    mov     rsi, [rel icn_cc26_rptr]
    call    icn_str_concat
    push    rax
    jmp     icon_25_fa1
    ; VAR result  id=29
icon_29_α:
    mov     rax, [rbp-24]
    push    rax
    jmp     icon_25_fa2
icon_29_β:
    jmp     icon_19_else
icon_25_α:
    jmp     icon_26_α
icon_25_fa1:
    pop     rax
    mov     [rel icn_find_s1_25], rax
    jmp     icon_29_α
icon_25_fa2:
    pop     rax
    mov     [rel icn_find_s2_25], rax
    mov     qword [rel icn_find_pos_25], 0
    jmp     icon_25_fchk
icon_25_β:
    jmp     icon_25_fchk
icon_25_fchk:
    mov     rdi, [rel icn_find_s1_25]
    mov     rsi, [rel icn_find_s2_25]
    mov     rdx, [rel icn_find_pos_25]
    call    icn_str_find
    test    rax, rax
    jz      icon_19_else
    mov     [rel icn_find_pos_25], rax
    push    rax
    jmp     icon_19_then
icon_19_then:
    add     rsp, 8
    jmp     icon_20_α
icon_19_else:
    jmp     icon_24_α
icon_19_α:
    jmp     icon_25_α
icon_19_β:
    jmp     icon_25_β
    jmp     icon_19_α
icon_16_top:
    jmp     icon_17_α
icon_16_α:
    jmp     icon_17_α
icon_16_β:
    jmp     icon_14_α
    ; CALL repl  id=31
icon_31_α:
    jmp     icon_16_α
icon_31_β:
    jmp     icon_16_α
icon_30_α:
    jmp     icon_31_α
icon_30_β:
    jmp     icon_31_β
icon_30_store:
    pop     rax
    mov     [rbp-24], rax
    jmp     icon_16_α
    ; SUB  id=33
    ; INT 1  id=34
icon_34_α:
    push    1
    jmp     icon_33_compute
icon_34_β:
    jmp     icon_33_lb
    ; VAR n  id=35
icon_35_α:
    mov     rax, [rbp-16]
    push    rax
    jmp     icon_33_lstore
icon_35_β:
    jmp     icon_30_α
icon_33_lb:
    jmp     icon_35_β
icon_33_α:
    mov     qword [rbp-96], 0
    jmp     icon_35_α
icon_33_β:
    mov     qword [rbp-96], 1
    jmp     icon_35_α
icon_33_lstore:
    pop     rax
    mov     [rbp-88], rax
    cmp     qword [rbp-96], 0
    je      icon_34_α
    jmp     icon_34_β
icon_33_compute:
    pop     rax
    mov     rcx, [rbp-88]
    sub     rcx, rax
    push    rcx
    jmp     icon_32_store
icon_32_α:
    jmp     icon_33_α
icon_32_β:
    jmp     icon_33_β
icon_32_store:
    pop     rax
    mov     [rbp-32], rax
    jmp     icon_30_α
    ; UNIMPL SIZE id=38
icon_38_α:
    jmp     icon_32_α
icon_38_β:
    jmp     icon_32_α
icon_37_α:
    jmp     icon_38_α
icon_37_β:
    jmp     icon_38_β
icon_37_store:
    pop     rax
    mov     [rbp-56], rax
    jmp     icon_36_store
icon_36_α:
    jmp     icon_37_α
icon_36_β:
    jmp     icon_37_β
icon_36_store:
    pop     rax
    mov     [rbp-40], rax
    jmp     icon_32_α
icn_meander:
    push    rbp
    mov     rbp, rsp
    sub     rsp, 112
    call    icn_pop
    mov     [rbp-16], rax
    call    icn_pop
    mov     [rbp-8], rax
    jmp     icon_36_α
icn_meander_ret:
    add     rsp, 112
    pop     rbp
    ret
icn_meander_done:
    mov     byte [rel icn_failed], 1
    add     rsp, 112
    pop     rbp
    ret
