; Auto-generated by icon_emit.c — Tiny-ICON Byrd Box x64
bits 64
default rel

section .rodata
icn_str_0:  db  121, 101, 115, 0
icn_str_1:  db  108, 101, 118, 101, 108, 0
icn_str_2:  db  104, 101, 108, 108, 111, 0
icn_str_3:  db  114, 97, 99, 101, 99, 97, 114, 0

section .bss
    icn_retval: resq 1
    icn_gvar_j: resq 1
    icn_gvar_i: resq 1
    icn_failed: resb 1
    icn_suspended: resb 1
    icn_suspend_resume: resq 1
    icn_suspend_rbp: resq 1

section .text
    global _start
    extern icn_write_int
    extern icn_write_str
    extern icn_push
    extern icn_pop
    extern icn_str_concat
    extern icn_str_eq
    extern icn_any
    extern icn_many
    extern icn_upto
    extern icn_str_find
    extern icn_match
    extern icn_tab
    extern icn_move
    extern icn_subject
    extern icn_pos

_start:
    call    icn_main
    mov     rax, 60
    xor     rdi, rdi
    syscall


; === procedure palindrome ===
icon_1_α:
    lea     rdi, [rel icn_str_0]
    jmp     icon_0_ret_store
icon_1_β:
    jmp     icon_0_ret_store
icon_0_α:
    jmp     icon_1_α
icon_0_β:
    jmp     icn_palindrome_ret
icon_0_ret_store:
    pop     rax
    mov     [rel icn_retval], rax
    mov     byte [rel icn_failed], 0
    jmp     icn_palindrome_ret
    ; WHILE  id=2
    ; LT  id=3
    ; VAR j  id=4
icon_4_α:
    mov     rax, [rel icn_gvar_j]
    push    rax
    jmp     icon_3_check
icon_4_β:
    jmp     icon_3_lb
    ; VAR i  id=5
icon_5_α:
    mov     rax, [rel icn_gvar_i]
    push    rax
    jmp     icon_3_lstore
icon_5_β:
    jmp     icon_0_α
icon_3_lb:
    jmp     icon_5_β
icon_3_α:
    jmp     icon_5_α
icon_3_β:
    jmp     icon_4_β
icon_3_lstore:
    pop     rax
    mov     [rbp-16], rax
    jmp     icon_4_α
icon_3_check:
    pop     rcx
    mov     rax, [rbp-16]
    cmp     rax, rcx
    jge      icon_4_β
    push    rcx
    jmp     icon_2_condok
icon_2_condok:
    add     rsp, 8
    ; UNIMPL SEQ_EXPR id=6
icon_6_α:
    jmp     icon_2_top
icon_6_β:
    jmp     icon_2_top
    jmp     icon_6_α
icon_2_top:
    jmp     icon_3_α
icon_2_α:
    jmp     icon_3_α
icon_2_β:
    jmp     icon_0_α
    ; UNIMPL SIZE id=8
icon_8_α:
    jmp     icon_2_α
icon_8_β:
    jmp     icon_2_α
icon_7_α:
    jmp     icon_8_α
icon_7_β:
    jmp     icon_8_β
icon_7_store:
    pop     rax
    mov     [rel icn_gvar_j], rax
    jmp     icon_2_α
    ; INT 1  id=10
icon_10_α:
    push    1
    jmp     icon_9_store
icon_10_β:
    jmp     icon_7_α
icon_9_α:
    jmp     icon_10_α
icon_9_β:
    jmp     icon_10_β
icon_9_store:
    pop     rax
    mov     [rel icn_gvar_i], rax
    jmp     icon_7_α
    ; CALL map  id=12
icon_12_α:
    jmp     icon_9_α
icon_12_β:
    jmp     icon_9_α
icon_11_α:
    jmp     icon_12_α
icon_11_β:
    jmp     icon_12_β
icon_11_store:
    pop     rax
    mov     [rbp-8], rax
    jmp     icon_9_α
icn_palindrome:
    push    rbp
    mov     rbp, rsp
    sub     rsp, 32
    call    icn_pop
    mov     [rbp-8], rax
    jmp     icon_11_α
icn_palindrome_ret:
    add     rsp, 32
    pop     rbp
    ret
icn_palindrome_done:
    mov     byte [rel icn_failed], 1
    add     rsp, 32
    pop     rbp
    ret

; === procedure main ===
    ; CALL write  id=13
    ; CALL palindrome  id=14
icon_15_α:
    lea     rdi, [rel icn_str_1]
    jmp     icon_14_push0
icon_15_β:
    jmp     icn_main_done
icon_14_push0:
    pop     rdi
    call    icn_push
    jmp     icon_14_docall
icon_14_α:
    jmp     icon_15_α
icon_14_β:
    jmp     icn_main_done
icon_14_docall:
    call    icn_palindrome
    movzx   rax, byte [rel icn_failed]
    test    rax, rax
    jnz     icn_main_done
    mov     rax, [rel icn_retval]
    push    rax
    jmp     icon_13_call
icon_13_α:
    jmp     icon_14_α
icon_13_β:
    jmp     icon_14_β
icon_13_call:
    pop     rdi
    call    icn_write_int
    jmp     icn_main_done
    ; CALL write  id=16
    ; CALL palindrome  id=17
icon_18_α:
    lea     rdi, [rel icn_str_2]
    jmp     icon_17_push0
icon_18_β:
    jmp     icon_13_α
icon_17_push0:
    pop     rdi
    call    icn_push
    jmp     icon_17_docall
icon_17_α:
    jmp     icon_18_α
icon_17_β:
    jmp     icon_13_α
icon_17_docall:
    call    icn_palindrome
    movzx   rax, byte [rel icn_failed]
    test    rax, rax
    jnz     icon_13_α
    mov     rax, [rel icn_retval]
    push    rax
    jmp     icon_16_call
icon_16_α:
    jmp     icon_17_α
icon_16_β:
    jmp     icon_17_β
icon_16_call:
    pop     rdi
    call    icn_write_int
    jmp     icon_13_α
    ; CALL write  id=19
    ; CALL palindrome  id=20
icon_21_α:
    lea     rdi, [rel icn_str_3]
    jmp     icon_20_push0
icon_21_β:
    jmp     icon_16_α
icon_20_push0:
    pop     rdi
    call    icn_push
    jmp     icon_20_docall
icon_20_α:
    jmp     icon_21_α
icon_20_β:
    jmp     icon_16_α
icon_20_docall:
    call    icn_palindrome
    movzx   rax, byte [rel icn_failed]
    test    rax, rax
    jnz     icon_16_α
    mov     rax, [rel icn_retval]
    push    rax
    jmp     icon_19_call
icon_19_α:
    jmp     icon_20_α
icon_19_β:
    jmp     icon_20_β
icon_19_call:
    pop     rdi
    call    icn_write_int
    jmp     icon_16_α
icn_main:
    push    rbp
    mov     rbp, rsp
    jmp     icon_19_α
icn_main_done:
    mov     byte [rel icn_failed], 1
    pop     rbp
    ret
