; Auto-generated by icon_emit.c — Tiny-ICON Byrd Box x64
bits 64
default rel

section .rodata
icn_str_0:  db  32, 32, 0
icn_str_1:  db  115, 111, 108, 117, 116, 105, 111, 110, 32, 0

section .bss
    icn_retval: resq 1
    icon_21_I: resq 1
    icon_21_bound: resq 1
    icon_21_e1cur: resq 1
    icon_21_e2seen: resq 1
    icn_gvar_n: resq 1
    icn_gvar_qcount: resq 1
    icon_39_I: resq 1
    icon_39_bound: resq 1
    icon_39_e1cur: resq 1
    icon_39_e2seen: resq 1
    icn_gvar_down: resq 1
    icn_gvar_up: resq 1
    icn_gvar_rows: resq 1
    icn_gvar_placed: resq 1
    icn_failed: resb 1
    icn_suspended: resb 1
    icn_suspend_resume: resq 1
    icn_suspend_rbp: resq 1

section .text
    global _start
    extern icn_write_int
    extern icn_write_str
    extern icn_push
    extern icn_pop
    extern icn_str_concat
    extern icn_str_eq
    extern icn_any
    extern icn_many
    extern icn_upto
    extern icn_str_find
    extern icn_match
    extern icn_tab
    extern icn_move
    extern icn_subject
    extern icn_pos

_start:
    call    icn_main
    mov     rax, 60
    xor     rdi, rdi
    syscall


; === procedure safe ===
icon_0_α:
    mov     qword [rel icn_retval], 0
    mov     byte [rel icn_failed], 0
    jmp     icn_safe_ret
icon_0_β:
    jmp     icn_safe_ret
icon_2_α:
    mov     byte [rel icn_failed], 1
    jmp     icn_safe_done
icon_2_β:
    jmp     icon_0_α
    ; NE  id=3
    ; INT 0  id=4
icon_4_α:
    push    0
    jmp     icon_3_check
icon_4_β:
    jmp     icon_3_lb
    ; UNIMPL SUBSCRIPT id=5
icon_5_α:
    jmp     icon_1_else
icon_5_β:
    jmp     icon_1_else
icon_3_lb:
    jmp     icon_5_β
icon_3_α:
    jmp     icon_5_α
icon_3_β:
    jmp     icon_4_β
icon_3_lstore:
    pop     rax
    mov     [rbp-24], rax
    jmp     icon_4_α
icon_3_check:
    pop     rcx
    mov     rax, [rbp-24]
    cmp     rax, rcx
    je      icon_4_β
    push    rcx
    jmp     icon_1_then
icon_1_then:
    add     rsp, 8
    jmp     icon_2_α
icon_1_else:
    jmp     icon_0_α
icon_1_α:
    jmp     icon_3_α
icon_1_β:
    jmp     icon_3_β
icon_7_α:
    mov     byte [rel icn_failed], 1
    jmp     icn_safe_done
icon_7_β:
    jmp     icon_1_α
    ; NE  id=8
    ; INT 0  id=9
icon_9_α:
    push    0
    jmp     icon_8_check
icon_9_β:
    jmp     icon_8_lb
    ; UNIMPL SUBSCRIPT id=10
icon_10_α:
    jmp     icon_6_else
icon_10_β:
    jmp     icon_6_else
icon_8_lb:
    jmp     icon_10_β
icon_8_α:
    jmp     icon_10_α
icon_8_β:
    jmp     icon_9_β
icon_8_lstore:
    pop     rax
    mov     [rbp-32], rax
    jmp     icon_9_α
icon_8_check:
    pop     rcx
    mov     rax, [rbp-32]
    cmp     rax, rcx
    je      icon_9_β
    push    rcx
    jmp     icon_6_then
icon_6_then:
    add     rsp, 8
    jmp     icon_7_α
icon_6_else:
    jmp     icon_1_α
icon_6_α:
    jmp     icon_8_α
icon_6_β:
    jmp     icon_8_β
icon_12_α:
    mov     byte [rel icn_failed], 1
    jmp     icn_safe_done
icon_12_β:
    jmp     icon_6_α
    ; NE  id=13
    ; INT 0  id=14
icon_14_α:
    push    0
    jmp     icon_13_check
icon_14_β:
    jmp     icon_13_lb
    ; UNIMPL SUBSCRIPT id=15
icon_15_α:
    jmp     icon_11_else
icon_15_β:
    jmp     icon_11_else
icon_13_lb:
    jmp     icon_15_β
icon_13_α:
    jmp     icon_15_α
icon_13_β:
    jmp     icon_14_β
icon_13_lstore:
    pop     rax
    mov     [rbp-40], rax
    jmp     icon_14_α
icon_13_check:
    pop     rcx
    mov     rax, [rbp-40]
    cmp     rax, rcx
    je      icon_14_β
    push    rcx
    jmp     icon_11_then
icon_11_then:
    add     rsp, 8
    jmp     icon_12_α
icon_11_else:
    jmp     icon_6_α
icon_11_α:
    jmp     icon_13_α
icon_11_β:
    jmp     icon_13_β
icn_safe:
    push    rbp
    mov     rbp, rsp
    sub     rsp, 48
    call    icn_pop
    mov     [rbp-16], rax
    call    icn_pop
    mov     [rbp-8], rax
    jmp     icon_11_α
icn_safe_ret:
    add     rsp, 48
    pop     rbp
    ret
icn_safe_done:
    mov     byte [rel icn_failed], 1
    add     rsp, 48
    pop     rbp
    ret

; === procedure show ===
    ; CALL write  id=16
icon_17_α:
    lea     rdi, [rel icn_str_0]
    jmp     icon_16_call
icon_17_β:
    jmp     icn_show_done
icon_16_α:
    jmp     icon_17_α
icon_16_β:
    jmp     icon_17_β
icon_16_call:
    call    icn_write_str
    jmp     icn_show_done
    ; EVERY  id=18
    ; UNIMPL SEQ_EXPR id=19
icon_19_α:
    jmp     icon_18_genb
icon_19_β:
    jmp     icon_18_genb
    ; TO  id=21
    ; VAR n  id=22
icon_22_α:
    mov     rax, [rel icn_gvar_n]
    push    rax
    jmp     icon_21_init
icon_22_β:
    jmp     icon_21_e1b
    ; INT 1  id=23
icon_23_α:
    push    1
    jmp     icon_22_α
icon_23_β:
    jmp     icon_16_α
icon_21_e1b:
    mov     qword [rel icon_21_e2seen], 0
    jmp     icon_23_β
icon_21_e2b:
    jmp     icon_22_β
icon_21_α:
    mov     qword [rel icon_21_e2seen], 0
    jmp     icon_23_α
icon_21_β:
    inc     qword [rel icon_21_I]
    jmp     icon_21_code
icon_21_init:
    pop     rax
    mov     [rel icon_21_bound], rax
    cmp     qword [rel icon_21_e2seen], 0
    jne     icon_21_init_e2adv
    pop     rax
    mov     [rel icon_21_e1cur], rax
    mov     [rel icon_21_I], rax
    mov     qword [rel icon_21_e2seen], 1
    jmp     icon_21_code
icon_21_init_e2adv:
    mov     rax, [rel icon_21_e1cur]
    mov     [rel icon_21_I], rax
    jmp     icon_21_code
icon_21_code:
    mov     rax, [rel icon_21_I]
    cmp     rax, [rel icon_21_bound]
    jg      icon_21_e2b
    push    rax
    jmp     icon_20_store
icon_20_α:
    jmp     icon_21_α
icon_20_β:
    jmp     icon_21_β
icon_20_store:
    pop     rax
    mov     [rbp-24], rax
    jmp     icon_18_body
icon_18_body:
    jmp     icon_19_α
icon_18_genb:
    jmp     icon_20_β
icon_18_α:
    jmp     icon_20_α
icon_18_β:
    jmp     icon_16_α
    ; CALL write  id=24
icon_25_α:
    lea     rdi, [rel icn_str_1]
    jmp     icon_24_call
icon_25_β:
    jmp     icon_18_α
icon_24_α:
    jmp     icon_25_α
icon_24_β:
    jmp     icon_25_β
icon_24_call:
    call    icn_write_str
    jmp     icon_18_α
    ; CALL repl  id=27
icon_27_α:
    jmp     icon_24_α
icon_27_β:
    jmp     icon_24_α
icon_26_α:
    jmp     icon_27_α
icon_26_β:
    jmp     icon_27_β
icon_26_store:
    pop     rax
    mov     [rbp-8], rax
    jmp     icon_24_α
    ; ADD  id=29
    ; INT 1  id=30
icon_30_α:
    push    1
    jmp     icon_29_compute
icon_30_β:
    jmp     icon_29_lb
    ; VAR qcount  id=31
icon_31_α:
    mov     rax, [rel icn_gvar_qcount]
    push    rax
    jmp     icon_29_lstore
icon_31_β:
    jmp     icon_26_α
icon_29_lb:
    jmp     icon_31_β
icon_29_α:
    mov     qword [rbp-40], 0
    jmp     icon_31_α
icon_29_β:
    mov     qword [rbp-40], 1
    jmp     icon_31_α
icon_29_lstore:
    pop     rax
    mov     [rbp-32], rax
    cmp     qword [rbp-40], 0
    je      icon_30_α
    jmp     icon_30_β
icon_29_compute:
    pop     rax
    mov     rcx, [rbp-32]
    add     rcx, rax
    push    rcx
    jmp     icon_28_aug_store
icon_28_α:
    jmp     icon_29_α
icon_28_β:
    jmp     icon_29_β
icon_28_aug_store:
    pop     rax
    mov     [rel icn_gvar_qcount], rax
    jmp     icon_26_α
icn_show:
    push    rbp
    mov     rbp, rsp
    sub     rsp, 48
    jmp     icon_28_α
icn_show_ret:
    add     rsp, 48
    pop     rbp
    ret
icn_show_done:
    mov     byte [rel icn_failed], 1
    add     rsp, 48
    pop     rbp
    ret

; === procedure try_col ===
    ; EVERY  id=32
    ; UNIMPL SEQ_EXPR id=34
icon_34_α:
    jmp     icon_32_genb
icon_34_β:
    jmp     icon_32_genb
    ; CALL safe  id=35
    ; VAR r  id=36
icon_36_α:
    mov     rax, [rbp-16]
    push    rax
    jmp     icon_35_push1
icon_36_β:
    jmp     icon_33_else
icon_35_push1:
    pop     rdi
    call    icn_push
    jmp     icon_35_docall
    ; VAR c  id=37
icon_37_α:
    mov     rax, [rbp-8]
    push    rax
    jmp     icon_35_push0
icon_37_β:
    jmp     icon_33_else
icon_35_push0:
    pop     rdi
    call    icn_push
    jmp     icon_36_α
icon_35_α:
    jmp     icon_37_α
icon_35_β:
    jmp     icon_33_else
icon_35_docall:
    call    icn_safe
    movzx   rax, byte [rel icn_failed]
    test    rax, rax
    jnz     icon_33_else
    mov     rax, [rel icn_retval]
    push    rax
    jmp     icon_33_then
icon_33_then:
    add     rsp, 8
    jmp     icon_34_α
icon_33_else:
    jmp     icon_32_genb
icon_33_α:
    jmp     icon_35_α
icon_33_β:
    jmp     icon_35_β
    ; TO  id=39
    ; VAR n  id=40
icon_40_α:
    mov     rax, [rel icn_gvar_n]
    push    rax
    jmp     icon_39_init
icon_40_β:
    jmp     icon_39_e1b
    ; INT 1  id=41
icon_41_α:
    push    1
    jmp     icon_40_α
icon_41_β:
    jmp     icn_try_col_done
icon_39_e1b:
    mov     qword [rel icon_39_e2seen], 0
    jmp     icon_41_β
icon_39_e2b:
    jmp     icon_40_β
icon_39_α:
    mov     qword [rel icon_39_e2seen], 0
    jmp     icon_41_α
icon_39_β:
    inc     qword [rel icon_39_I]
    jmp     icon_39_code
icon_39_init:
    pop     rax
    mov     [rel icon_39_bound], rax
    cmp     qword [rel icon_39_e2seen], 0
    jne     icon_39_init_e2adv
    pop     rax
    mov     [rel icon_39_e1cur], rax
    mov     [rel icon_39_I], rax
    mov     qword [rel icon_39_e2seen], 1
    jmp     icon_39_code
icon_39_init_e2adv:
    mov     rax, [rel icon_39_e1cur]
    mov     [rel icon_39_I], rax
    jmp     icon_39_code
icon_39_code:
    mov     rax, [rel icon_39_I]
    cmp     rax, [rel icon_39_bound]
    jg      icon_39_e2b
    push    rax
    jmp     icon_38_store
icon_38_α:
    jmp     icon_39_α
icon_38_β:
    jmp     icon_39_β
icon_38_store:
    pop     rax
    mov     [rbp-16], rax
    jmp     icon_32_body
icon_32_body:
    jmp     icon_33_α
icon_32_genb:
    jmp     icon_38_β
icon_32_α:
    jmp     icon_38_α
icon_32_β:
    jmp     icn_try_col_done
    ; UNIMPL SEQ_EXPR id=43
icon_43_α:
    jmp     icon_32_α
icon_43_β:
    jmp     icon_32_α
    ; GT  id=44
    ; VAR n  id=45
icon_45_α:
    mov     rax, [rel icn_gvar_n]
    push    rax
    jmp     icon_44_check
icon_45_β:
    jmp     icon_44_lb
    ; VAR c  id=46
icon_46_α:
    mov     rax, [rbp-8]
    push    rax
    jmp     icon_44_lstore
icon_46_β:
    jmp     icon_42_else
icon_44_lb:
    jmp     icon_46_β
icon_44_α:
    jmp     icon_46_α
icon_44_β:
    jmp     icon_45_β
icon_44_lstore:
    pop     rax
    mov     [rbp-24], rax
    jmp     icon_45_α
icon_44_check:
    pop     rcx
    mov     rax, [rbp-24]
    cmp     rax, rcx
    jle      icon_45_β
    push    rcx
    jmp     icon_42_then
icon_42_then:
    add     rsp, 8
    jmp     icon_43_α
icon_42_else:
    jmp     icon_32_α
icon_42_α:
    jmp     icon_44_α
icon_42_β:
    jmp     icon_44_β
icn_try_col:
    push    rbp
    mov     rbp, rsp
    sub     rsp, 32
    call    icn_pop
    mov     [rbp-8], rax
    jmp     icon_42_α
icn_try_col_ret:
    add     rsp, 32
    pop     rbp
    ret
icn_try_col_done:
    mov     byte [rel icn_failed], 1
    add     rsp, 32
    pop     rbp
    ret

; === procedure main ===
    ; CALL write  id=47
    ; VAR qcount  id=48
icon_48_α:
    mov     rax, [rel icn_gvar_qcount]
    push    rax
    jmp     icon_47_call
icon_48_β:
    jmp     icn_main_done
icon_47_α:
    jmp     icon_48_α
icon_47_β:
    jmp     icon_48_β
icon_47_call:
    pop     rdi
    call    icn_write_int
    jmp     icn_main_done
    ; CALL try_col  id=49
    ; INT 1  id=50
icon_50_α:
    push    1
    jmp     icon_49_push0
icon_50_β:
    jmp     icon_47_α
icon_49_push0:
    pop     rdi
    call    icn_push
    jmp     icon_49_docall
icon_49_α:
    jmp     icon_50_α
icon_49_β:
    jmp     icon_47_α
icon_49_docall:
    call    icn_try_col
    movzx   rax, byte [rel icn_failed]
    test    rax, rax
    jnz     icon_47_α
    mov     rax, [rel icn_retval]
    push    rax
    jmp     icon_47_α
    ; CALL write  id=51
    ; VAR n  id=52
icon_52_α:
    mov     rax, [rel icn_gvar_n]
    push    rax
    jmp     icon_51_call
icon_52_β:
    jmp     icon_49_α
icon_51_α:
    jmp     icon_52_α
icon_51_β:
    jmp     icon_52_β
icon_51_call:
    pop     rdi
    call    icn_write_int
    jmp     icon_49_α
    ; INT 0  id=54
icon_54_α:
    push    0
    jmp     icon_53_store
icon_54_β:
    jmp     icon_51_α
icon_53_α:
    jmp     icon_54_α
icon_53_β:
    jmp     icon_54_β
icon_53_store:
    pop     rax
    mov     [rel icn_gvar_qcount], rax
    jmp     icon_51_α
    ; CALL list  id=56
icon_56_α:
    jmp     icon_53_α
icon_56_β:
    jmp     icon_53_α
icon_55_α:
    jmp     icon_56_α
icon_55_β:
    jmp     icon_56_β
icon_55_store:
    pop     rax
    mov     [rel icn_gvar_down], rax
    jmp     icon_53_α
    ; CALL list  id=58
icon_58_α:
    jmp     icon_55_α
icon_58_β:
    jmp     icon_55_α
icon_57_α:
    jmp     icon_58_α
icon_57_β:
    jmp     icon_58_β
icon_57_store:
    pop     rax
    mov     [rel icn_gvar_up], rax
    jmp     icon_55_α
    ; CALL list  id=60
icon_60_α:
    jmp     icon_57_α
icon_60_β:
    jmp     icon_57_α
icon_59_α:
    jmp     icon_60_α
icon_59_β:
    jmp     icon_60_β
icon_59_store:
    pop     rax
    mov     [rel icn_gvar_rows], rax
    jmp     icon_57_α
    ; CALL list  id=62
icon_62_α:
    jmp     icon_59_α
icon_62_β:
    jmp     icon_59_α
icon_61_α:
    jmp     icon_62_α
icon_61_β:
    jmp     icon_62_β
icon_61_store:
    pop     rax
    mov     [rel icn_gvar_placed], rax
    jmp     icon_59_α
    ; INT 6  id=65
icon_65_α:
    push    6
    jmp     icon_63_store
icon_65_β:
    jmp     icon_61_α
    ; CALL integer  id=66
icon_66_α:
    jmp     icon_65_α
icon_66_β:
    jmp     icon_65_α
icon_64_α:
    jmp     icon_66_α
icon_64_β:
    jmp     icon_66_β
icon_63_α:
    jmp     icon_64_α
icon_63_β:
    jmp     icon_64_β
icon_63_store:
    pop     rax
    mov     [rel icn_gvar_n], rax
    jmp     icon_61_α
icn_main:
    push    rbp
    mov     rbp, rsp
    sub     rsp, 16
    jmp     icon_63_α
icn_main_done:
    mov     byte [rel icn_failed], 1
    add     rsp, 16
    pop     rbp
    ret
