; Auto-generated by icon_emit.c — Tiny-ICON Byrd Box x64
bits 64
default rel

section .rodata
icn_str_0:  db  , 0

section .bss
    icn_retval: resq 1
    icn_gvar_result: resq 1
    icon_9_I: resq 1
    icon_9_bound: resq 1
    icon_9_e1cur: resq 1
    icon_9_e2seen: resq 1
    icn_gvar_i: resq 1
    icn_gvar_syms: resq 1
    icn_gvar_vals: resq 1
    icn_failed: resb 1
    icn_suspended: resb 1
    icn_suspend_resume: resq 1
    icn_suspend_rbp: resq 1

section .text
    global _start
    extern icn_write_int
    extern icn_write_str
    extern icn_push
    extern icn_pop
    extern icn_str_concat
    extern icn_str_eq
    extern icn_any
    extern icn_many
    extern icn_upto
    extern icn_str_find
    extern icn_match
    extern icn_tab
    extern icn_move
    extern icn_subject
    extern icn_pos

_start:
    call    icn_main
    mov     rax, 60
    xor     rdi, rdi
    syscall


; === procedure roman ===
    ; VAR result  id=1
icon_1_α:
    mov     rax, [rel icn_gvar_result]
    push    rax
    jmp     icon_0_ret_store
icon_1_β:
    jmp     icon_0_ret_store
icon_0_α:
    jmp     icon_1_α
icon_0_β:
    jmp     icn_roman_ret
icon_0_ret_store:
    pop     rax
    mov     [rel icn_retval], rax
    mov     byte [rel icn_failed], 0
    jmp     icn_roman_ret
    ; EVERY  id=2
    ; WHILE  id=3
    ; GE  id=4
    ; UNIMPL SUBSCRIPT id=5
icon_5_α:
    jmp     icon_4_lb
icon_5_β:
    jmp     icon_4_lb
    ; VAR n  id=6
icon_6_α:
    mov     rax, [rbp-8]
    push    rax
    jmp     icon_4_lstore
icon_6_β:
    jmp     icon_2_genb
icon_4_lb:
    jmp     icon_6_β
icon_4_α:
    jmp     icon_6_α
icon_4_β:
    jmp     icon_5_β
icon_4_lstore:
    pop     rax
    mov     [rbp-16], rax
    jmp     icon_5_α
icon_4_check:
    pop     rcx
    mov     rax, [rbp-16]
    cmp     rax, rcx
    jl      icon_5_β
    push    rcx
    jmp     icon_3_condok
icon_3_condok:
    add     rsp, 8
    ; UNIMPL SEQ_EXPR id=7
icon_7_α:
    jmp     icon_3_top
icon_7_β:
    jmp     icon_3_top
    jmp     icon_7_α
icon_3_top:
    jmp     icon_4_α
icon_3_α:
    jmp     icon_4_α
icon_3_β:
    jmp     icon_2_genb
    ; TO  id=9
    ; UNIMPL SIZE id=10
icon_10_α:
    jmp     icon_9_e1b
icon_10_β:
    jmp     icon_9_e1b
    ; INT 1  id=11
icon_11_α:
    push    1
    jmp     icon_10_α
icon_11_β:
    jmp     icon_0_α
icon_9_e1b:
    mov     qword [rel icon_9_e2seen], 0
    jmp     icon_11_β
icon_9_e2b:
    jmp     icon_10_β
icon_9_α:
    mov     qword [rel icon_9_e2seen], 0
    jmp     icon_11_α
icon_9_β:
    inc     qword [rel icon_9_I]
    jmp     icon_9_code
icon_9_init:
    pop     rax
    mov     [rel icon_9_bound], rax
    cmp     qword [rel icon_9_e2seen], 0
    jne     icon_9_init_e2adv
    pop     rax
    mov     [rel icon_9_e1cur], rax
    mov     [rel icon_9_I], rax
    mov     qword [rel icon_9_e2seen], 1
    jmp     icon_9_code
icon_9_init_e2adv:
    mov     rax, [rel icon_9_e1cur]
    mov     [rel icon_9_I], rax
    jmp     icon_9_code
icon_9_code:
    mov     rax, [rel icon_9_I]
    cmp     rax, [rel icon_9_bound]
    jg      icon_9_e2b
    push    rax
    jmp     icon_8_store
icon_8_α:
    jmp     icon_9_α
icon_8_β:
    jmp     icon_9_β
icon_8_store:
    pop     rax
    mov     [rel icn_gvar_i], rax
    jmp     icon_2_body
icon_2_body:
    jmp     icon_3_α
icon_2_genb:
    jmp     icon_8_β
icon_2_α:
    jmp     icon_8_α
icon_2_β:
    jmp     icon_0_α
icon_13_α:
    lea     rdi, [rel icn_str_0]
    jmp     icon_12_store
icon_13_β:
    jmp     icon_2_α
icon_12_α:
    jmp     icon_13_α
icon_12_β:
    jmp     icon_13_β
icon_12_store:
    ; str assign: rdi already has pointer
    mov     [rel icn_gvar_result], rdi
    jmp     icon_2_α
    ; UNIMPL MAKELIST id=15
icon_15_α:
    jmp     icon_12_α
icon_15_β:
    jmp     icon_12_α
icon_14_α:
    jmp     icon_15_α
icon_14_β:
    jmp     icon_15_β
icon_14_store:
    pop     rax
    mov     [rel icn_gvar_syms], rax
    jmp     icon_12_α
    ; UNIMPL MAKELIST id=17
icon_17_α:
    jmp     icon_14_α
icon_17_β:
    jmp     icon_14_α
icon_16_α:
    jmp     icon_17_α
icon_16_β:
    jmp     icon_17_β
icon_16_store:
    pop     rax
    mov     [rel icn_gvar_vals], rax
    jmp     icon_14_α
icn_roman:
    push    rbp
    mov     rbp, rsp
    sub     rsp, 32
    call    icn_pop
    mov     [rbp-8], rax
    jmp     icon_16_α
icn_roman_ret:
    add     rsp, 32
    pop     rbp
    ret
icn_roman_done:
    mov     byte [rel icn_failed], 1
    add     rsp, 32
    pop     rbp
    ret

; === procedure main ===
    ; CALL write  id=18
    ; CALL roman  id=19
    ; INT 9  id=20
icon_20_α:
    push    9
    jmp     icon_19_push0
icon_20_β:
    jmp     icn_main_done
icon_19_push0:
    pop     rdi
    call    icn_push
    jmp     icon_19_docall
icon_19_α:
    jmp     icon_20_α
icon_19_β:
    jmp     icn_main_done
icon_19_docall:
    call    icn_roman
    movzx   rax, byte [rel icn_failed]
    test    rax, rax
    jnz     icn_main_done
    mov     rax, [rel icn_retval]
    push    rax
    jmp     icon_18_call
icon_18_α:
    jmp     icon_19_α
icon_18_β:
    jmp     icon_19_β
icon_18_call:
    pop     rdi
    call    icn_write_int
    jmp     icn_main_done
    ; CALL write  id=21
    ; CALL roman  id=22
    ; INT 42  id=23
icon_23_α:
    push    42
    jmp     icon_22_push0
icon_23_β:
    jmp     icon_18_α
icon_22_push0:
    pop     rdi
    call    icn_push
    jmp     icon_22_docall
icon_22_α:
    jmp     icon_23_α
icon_22_β:
    jmp     icon_18_α
icon_22_docall:
    call    icn_roman
    movzx   rax, byte [rel icn_failed]
    test    rax, rax
    jnz     icon_18_α
    mov     rax, [rel icn_retval]
    push    rax
    jmp     icon_21_call
icon_21_α:
    jmp     icon_22_α
icon_21_β:
    jmp     icon_22_β
icon_21_call:
    pop     rdi
    call    icn_write_int
    jmp     icon_18_α
    ; CALL write  id=24
    ; CALL roman  id=25
    ; INT 1776  id=26
icon_26_α:
    push    1776
    jmp     icon_25_push0
icon_26_β:
    jmp     icon_21_α
icon_25_push0:
    pop     rdi
    call    icn_push
    jmp     icon_25_docall
icon_25_α:
    jmp     icon_26_α
icon_25_β:
    jmp     icon_21_α
icon_25_docall:
    call    icn_roman
    movzx   rax, byte [rel icn_failed]
    test    rax, rax
    jnz     icon_21_α
    mov     rax, [rel icn_retval]
    push    rax
    jmp     icon_24_call
icon_24_α:
    jmp     icon_25_α
icon_24_β:
    jmp     icon_25_β
icon_24_call:
    pop     rdi
    call    icn_write_int
    jmp     icon_21_α
icn_main:
    push    rbp
    mov     rbp, rsp
    jmp     icon_24_α
icn_main_done:
    mov     byte [rel icn_failed], 1
    pop     rbp
    ret
