; Auto-generated by icon_emit.c — Tiny-ICON Byrd Box x64
bits 64
default rel

section .rodata
icn_str_0:  db  , 0

section .bss
    icn_retval: resq 1
    icn_gvar_out: resq 1
    icon_9_I: resq 1
    icon_9_bound: resq 1
    icon_9_e1cur: resq 1
    icon_9_e2seen: resq 1
    icn_gvar_limit: resq 1
    icn_gvar_i: resq 1
    icon_20_I: resq 1
    icon_20_bound: resq 1
    icon_20_step: resq 1
    icn_gvar_j: resq 1
    icon_30_I: resq 1
    icon_30_bound: resq 1
    icon_30_e1cur: resq 1
    icon_30_e2seen: resq 1
    icn_gvar_sieve: resq 1
    icn_failed: resb 1
    icn_suspended: resb 1
    icn_suspend_resume: resq 1
    icn_suspend_rbp: resq 1

section .text
    global _start
    extern icn_write_int
    extern icn_write_str
    extern icn_push
    extern icn_pop
    extern icn_str_concat
    extern icn_str_eq
    extern icn_any
    extern icn_many
    extern icn_upto
    extern icn_str_find
    extern icn_match
    extern icn_tab
    extern icn_move
    extern icn_subject
    extern icn_pos

_start:
    call    icn_main
    mov     rax, 60
    xor     rdi, rdi
    syscall


; === procedure main ===
    ; CALL write  id=0
    ; VAR out  id=1
icon_1_α:
    mov     rax, [rel icn_gvar_out]
    push    rax
    jmp     icon_0_call
icon_1_β:
    jmp     icn_main_done
icon_0_α:
    jmp     icon_1_α
icon_0_β:
    jmp     icon_1_β
icon_0_call:
    pop     rdi
    call    icn_write_int
    jmp     icn_main_done
    ; EVERY  id=2
    ; UNIMPL SEQ_EXPR id=4
icon_4_α:
    jmp     icon_2_genb
icon_4_β:
    jmp     icon_2_genb
    ; EQ  id=5
    ; INT 1  id=6
icon_6_α:
    push    1
    jmp     icon_5_check
icon_6_β:
    jmp     icon_5_lb
    ; UNIMPL SUBSCRIPT id=7
icon_7_α:
    jmp     icon_3_else
icon_7_β:
    jmp     icon_3_else
icon_5_lb:
    jmp     icon_7_β
icon_5_α:
    jmp     icon_7_α
icon_5_β:
    jmp     icon_6_β
icon_5_lstore:
    pop     rax
    mov     [rbp-8], rax
    jmp     icon_6_α
icon_5_check:
    pop     rcx
    mov     rax, [rbp-8]
    cmp     rax, rcx
    jne      icon_6_β
    push    rcx
    jmp     icon_3_then
icon_3_then:
    add     rsp, 8
    jmp     icon_4_α
icon_3_else:
    jmp     icon_2_genb
icon_3_α:
    jmp     icon_5_α
icon_3_β:
    jmp     icon_5_β
    ; TO  id=9
    ; VAR limit  id=10
icon_10_α:
    mov     rax, [rel icn_gvar_limit]
    push    rax
    jmp     icon_9_init
icon_10_β:
    jmp     icon_9_e1b
    ; INT 2  id=11
icon_11_α:
    push    2
    jmp     icon_10_α
icon_11_β:
    jmp     icon_0_α
icon_9_e1b:
    mov     qword [rel icon_9_e2seen], 0
    jmp     icon_11_β
icon_9_e2b:
    jmp     icon_10_β
icon_9_α:
    mov     qword [rel icon_9_e2seen], 0
    jmp     icon_11_α
icon_9_β:
    inc     qword [rel icon_9_I]
    jmp     icon_9_code
icon_9_init:
    pop     rax
    mov     [rel icon_9_bound], rax
    cmp     qword [rel icon_9_e2seen], 0
    jne     icon_9_init_e2adv
    pop     rax
    mov     [rel icon_9_e1cur], rax
    mov     [rel icon_9_I], rax
    mov     qword [rel icon_9_e2seen], 1
    jmp     icon_9_code
icon_9_init_e2adv:
    mov     rax, [rel icon_9_e1cur]
    mov     [rel icon_9_I], rax
    jmp     icon_9_code
icon_9_code:
    mov     rax, [rel icon_9_I]
    cmp     rax, [rel icon_9_bound]
    jg      icon_9_e2b
    push    rax
    jmp     icon_8_store
icon_8_α:
    jmp     icon_9_α
icon_8_β:
    jmp     icon_9_β
icon_8_store:
    pop     rax
    mov     [rel icn_gvar_i], rax
    jmp     icon_2_body
icon_2_body:
    jmp     icon_3_α
icon_2_genb:
    jmp     icon_8_β
icon_2_α:
    jmp     icon_8_α
icon_2_β:
    jmp     icon_0_α
icon_13_α:
    lea     rdi, [rel icn_str_0]
    jmp     icon_12_store
icon_13_β:
    jmp     icon_2_α
icon_12_α:
    jmp     icon_13_α
icon_12_β:
    jmp     icon_13_β
icon_12_store:
    ; str assign: rdi already has pointer
    mov     [rel icn_gvar_out], rdi
    jmp     icon_2_α
    ; EVERY  id=14
    ; EVERY  id=16
    ; INT 0  id=18
icon_18_α:
    push    0
    jmp     icon_17_store
icon_18_β:
    jmp     icon_16_genb
icon_17_α:
    jmp     icon_18_α
icon_17_β:
    jmp     icon_18_β
icon_17_store:
    pop     rax
    jmp     icon_16_genb
    ; TO_BY  id=20
    ; VAR i  id=21
icon_21_α:
    mov     rax, [rel icn_gvar_i]
    push    rax
    jmp     icon_20_stepr
icon_21_β:
    jmp     icon_20_e2b
    ; VAR limit  id=22
icon_22_α:
    mov     rax, [rel icn_gvar_limit]
    push    rax
    jmp     icon_20_boundr
icon_22_β:
    jmp     icon_20_e1b
    ; MUL  id=23
    ; VAR i  id=24
icon_24_α:
    mov     rax, [rel icn_gvar_i]
    push    rax
    jmp     icon_23_compute
icon_24_β:
    jmp     icon_23_lb
    ; VAR i  id=25
icon_25_α:
    mov     rax, [rel icn_gvar_i]
    push    rax
    jmp     icon_23_lstore
icon_25_β:
    jmp     icon_14_genb
icon_23_lb:
    jmp     icon_25_β
icon_23_α:
    mov     qword [rbp-24], 0
    jmp     icon_25_α
icon_23_β:
    mov     qword [rbp-24], 1
    jmp     icon_25_α
icon_23_lstore:
    pop     rax
    mov     [rbp-16], rax
    cmp     qword [rbp-24], 0
    je      icon_24_α
    jmp     icon_24_β
icon_23_compute:
    pop     rax
    mov     rcx, [rbp-16]
    imul    rcx, rax
    push    rcx
    jmp     icon_20_startr
icon_20_startr:
    pop     rax
    mov     [rel icon_20_I], rax
    jmp     icon_22_α
icon_20_boundr:
    pop     rax
    mov     [rel icon_20_bound], rax
    jmp     icon_21_α
icon_20_stepr:
    pop     rax
    mov     [rel icon_20_step], rax
    jmp     icon_20_code
icon_20_e1b:
    jmp     icon_23_β
icon_20_e2b:
    jmp     icon_22_β
icon_20_α:
    jmp     icon_23_α
icon_20_β:
    mov     rax, [rel icon_20_step]
    add     [rel icon_20_I], rax
    jmp     icon_20_code
icon_20_init:
    jmp     icon_20_code
icon_20_code:
    mov     rax, [rel icon_20_I]
    cmp     rax, [rel icon_20_bound]
    jg      icon_20_e2b
    push    rax
    jmp     icon_19_store
icon_19_α:
    jmp     icon_20_α
icon_19_β:
    jmp     icon_20_β
icon_19_store:
    pop     rax
    mov     [rel icn_gvar_j], rax
    jmp     icon_16_body
icon_16_body:
    jmp     icon_17_α
icon_16_genb:
    jmp     icon_19_β
icon_16_α:
    jmp     icon_19_α
icon_16_β:
    jmp     icon_14_genb
    ; EQ  id=26
    ; INT 1  id=27
icon_27_α:
    push    1
    jmp     icon_26_check
icon_27_β:
    jmp     icon_26_lb
    ; UNIMPL SUBSCRIPT id=28
icon_28_α:
    jmp     icon_15_else
icon_28_β:
    jmp     icon_15_else
icon_26_lb:
    jmp     icon_28_β
icon_26_α:
    jmp     icon_28_α
icon_26_β:
    jmp     icon_27_β
icon_26_lstore:
    pop     rax
    mov     [rbp-32], rax
    jmp     icon_27_α
icon_26_check:
    pop     rcx
    mov     rax, [rbp-32]
    cmp     rax, rcx
    jne      icon_27_β
    push    rcx
    jmp     icon_15_then
icon_15_then:
    add     rsp, 8
    jmp     icon_16_α
icon_15_else:
    jmp     icon_14_genb
icon_15_α:
    jmp     icon_26_α
icon_15_β:
    jmp     icon_26_β
    ; TO  id=30
    ; VAR limit  id=31
icon_31_α:
    mov     rax, [rel icn_gvar_limit]
    push    rax
    jmp     icon_30_init
icon_31_β:
    jmp     icon_30_e1b
    ; INT 2  id=32
icon_32_α:
    push    2
    jmp     icon_31_α
icon_32_β:
    jmp     icon_12_α
icon_30_e1b:
    mov     qword [rel icon_30_e2seen], 0
    jmp     icon_32_β
icon_30_e2b:
    jmp     icon_31_β
icon_30_α:
    mov     qword [rel icon_30_e2seen], 0
    jmp     icon_32_α
icon_30_β:
    inc     qword [rel icon_30_I]
    jmp     icon_30_code
icon_30_init:
    pop     rax
    mov     [rel icon_30_bound], rax
    cmp     qword [rel icon_30_e2seen], 0
    jne     icon_30_init_e2adv
    pop     rax
    mov     [rel icon_30_e1cur], rax
    mov     [rel icon_30_I], rax
    mov     qword [rel icon_30_e2seen], 1
    jmp     icon_30_code
icon_30_init_e2adv:
    mov     rax, [rel icon_30_e1cur]
    mov     [rel icon_30_I], rax
    jmp     icon_30_code
icon_30_code:
    mov     rax, [rel icon_30_I]
    cmp     rax, [rel icon_30_bound]
    jg      icon_30_e2b
    push    rax
    jmp     icon_29_store
icon_29_α:
    jmp     icon_30_α
icon_29_β:
    jmp     icon_30_β
icon_29_store:
    pop     rax
    mov     [rel icn_gvar_i], rax
    jmp     icon_14_body
icon_14_body:
    jmp     icon_15_α
icon_14_genb:
    jmp     icon_29_β
icon_14_α:
    jmp     icon_29_α
icon_14_β:
    jmp     icon_12_α
    ; INT 0  id=34
icon_34_α:
    push    0
    jmp     icon_33_store
icon_34_β:
    jmp     icon_14_α
icon_33_α:
    jmp     icon_34_α
icon_33_β:
    jmp     icon_34_β
icon_33_store:
    pop     rax
    jmp     icon_14_α
    ; CALL list  id=36
icon_36_α:
    jmp     icon_33_α
icon_36_β:
    jmp     icon_33_α
icon_35_α:
    jmp     icon_36_α
icon_35_β:
    jmp     icon_36_β
icon_35_store:
    pop     rax
    mov     [rel icn_gvar_sieve], rax
    jmp     icon_33_α
    ; INT 50  id=38
icon_38_α:
    push    50
    jmp     icon_37_store
icon_38_β:
    jmp     icon_35_α
icon_37_α:
    jmp     icon_38_α
icon_37_β:
    jmp     icon_38_β
icon_37_store:
    pop     rax
    mov     [rel icn_gvar_limit], rax
    jmp     icon_35_α
icn_main:
    push    rbp
    mov     rbp, rsp
    sub     rsp, 48
    jmp     icon_37_α
icn_main_done:
    mov     byte [rel icn_failed], 1
    add     rsp, 48
    pop     rbp
    ret
