#!/usr/bin/env bash
# build_boxes.sh — assemble all bb_*.il sources into boxes.dll
#
# Usage:
#   bash src/runtime/boxes/build_boxes.sh
#   bash src/runtime/boxes/build_boxes.sh /path/to/output/boxes.dll
#
# Requires: ilasm (mono-complete)
# Output: boxes.dll (default: src/runtime/boxes/boxes.dll)
#
# AUTHORS: Lon Jones Cherryholmes · Jeffrey Cooper M.D. · Claude Sonnet 4.6
# SPRINT:  D-169

set -e
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUT="${1:-$SCRIPT_DIR/boxes.dll}"

# Ordered: foundation first, then boxes, executor last
IL_FILES=(
  "$SCRIPT_DIR/shared/bb_box.il"
  "$SCRIPT_DIR/lit/bb_lit.il"
  "$SCRIPT_DIR/seq/bb_seq.il"
  "$SCRIPT_DIR/alt/bb_alt.il"
  "$SCRIPT_DIR/arb/bb_arb.il"
  "$SCRIPT_DIR/arbno/bb_arbno.il"
  "$SCRIPT_DIR/any/bb_any.il"
  "$SCRIPT_DIR/any/bb_notany.il"
  "$SCRIPT_DIR/span/bb_span.il"
  "$SCRIPT_DIR/brk/bb_brk.il"
  "$SCRIPT_DIR/breakx/bb_breakx.il"
  "$SCRIPT_DIR/len/bb_len.il"
  "$SCRIPT_DIR/pos/bb_pos.il"
  "$SCRIPT_DIR/tab/bb_tab.il"
  "$SCRIPT_DIR/rem/bb_rem.il"
  "$SCRIPT_DIR/eps/bb_eps.il"
  "$SCRIPT_DIR/bal/bb_bal.il"
  "$SCRIPT_DIR/abort/bb_terminals.il"
  "$SCRIPT_DIR/not/bb_not.il"
  "$SCRIPT_DIR/interr/bb_interr.il"
  "$SCRIPT_DIR/capture/bb_capture.il"
  "$SCRIPT_DIR/atp/bb_atp.il"
  "$SCRIPT_DIR/dvar/bb_dvar.il"
  "$SCRIPT_DIR/shared/bb_executor.il"
)

# Verify all files exist
MISSING=0
for f in "${IL_FILES[@]}"; do
  if [ ! -f "$f" ]; then
    echo "MISSING: $f"
    MISSING=$((MISSING+1))
  fi
done
[ $MISSING -gt 0 ] && { echo "ERROR: $MISSING file(s) missing"; exit 1; }

# Concatenate all .il into a single translation unit with one .assembly directive
TMP="$(mktemp /tmp/boxes_combined_XXXXXX.il)"
trap "rm -f '$TMP'" EXIT

cat > "$TMP" << 'HEADER'
// boxes_combined.il — auto-generated by build_boxes.sh
// Single-assembly compilation of all Byrd box MSIL sources.
// Do not edit directly — edit bb_*.il sources and rebuild.

.assembly extern mscorlib {}
.assembly boxes {}
.module boxes.dll

HEADER

# Append each file, stripping per-file .assembly extern and .assembly directives
for f in "${IL_FILES[@]}"; do
  echo "// ===== $(basename $f) =====" >> "$TMP"
  grep -v '^\s*\.assembly' "$f" >> "$TMP"
  echo "" >> "$TMP"
done

echo "Assembling $(echo "${IL_FILES[@]}" | wc -w) IL files → $OUT"
ilasm "$TMP" /dll /output:"$OUT" /quiet

if [ $? -eq 0 ]; then
  echo "  OK  boxes.dll built: $OUT"
else
  echo "  FAIL  ilasm error — see output above"
  exit 1
fi
