#line 2 "snocone.lex.c"

#line 4 "snocone.lex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define sc__create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer sc__create_buffer
#endif

#ifdef yy_delete_buffer
#define sc__delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer sc__delete_buffer
#endif

#ifdef yy_scan_buffer
#define sc__scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer sc__scan_buffer
#endif

#ifdef yy_scan_string
#define sc__scan_string_ALREADY_DEFINED
#else
#define yy_scan_string sc__scan_string
#endif

#ifdef yy_scan_bytes
#define sc__scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes sc__scan_bytes
#endif

#ifdef yy_init_buffer
#define sc__init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer sc__init_buffer
#endif

#ifdef yy_flush_buffer
#define sc__flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer sc__flush_buffer
#endif

#ifdef yy_load_buffer_state
#define sc__load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state sc__load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define sc__switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer sc__switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define sc_push_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state sc_push_buffer_state
#endif

#ifdef yypop_buffer_state
#define sc_pop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state sc_pop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define sc_ensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack sc_ensure_buffer_stack
#endif

#ifdef yylex
#define sc_lex_ALREADY_DEFINED
#else
#define yylex sc_lex
#endif

#ifdef yyrestart
#define sc_restart_ALREADY_DEFINED
#else
#define yyrestart sc_restart
#endif

#ifdef yylex_init
#define sc_lex_init_ALREADY_DEFINED
#else
#define yylex_init sc_lex_init
#endif

#ifdef yylex_init_extra
#define sc_lex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra sc_lex_init_extra
#endif

#ifdef yylex_destroy
#define sc_lex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy sc_lex_destroy
#endif

#ifdef yyget_debug
#define sc_get_debug_ALREADY_DEFINED
#else
#define yyget_debug sc_get_debug
#endif

#ifdef yyset_debug
#define sc_set_debug_ALREADY_DEFINED
#else
#define yyset_debug sc_set_debug
#endif

#ifdef yyget_extra
#define sc_get_extra_ALREADY_DEFINED
#else
#define yyget_extra sc_get_extra
#endif

#ifdef yyset_extra
#define sc_set_extra_ALREADY_DEFINED
#else
#define yyset_extra sc_set_extra
#endif

#ifdef yyget_in
#define sc_get_in_ALREADY_DEFINED
#else
#define yyget_in sc_get_in
#endif

#ifdef yyset_in
#define sc_set_in_ALREADY_DEFINED
#else
#define yyset_in sc_set_in
#endif

#ifdef yyget_out
#define sc_get_out_ALREADY_DEFINED
#else
#define yyget_out sc_get_out
#endif

#ifdef yyset_out
#define sc_set_out_ALREADY_DEFINED
#else
#define yyset_out sc_set_out
#endif

#ifdef yyget_leng
#define sc_get_leng_ALREADY_DEFINED
#else
#define yyget_leng sc_get_leng
#endif

#ifdef yyget_text
#define sc_get_text_ALREADY_DEFINED
#else
#define yyget_text sc_get_text
#endif

#ifdef yyget_lineno
#define sc_get_lineno_ALREADY_DEFINED
#else
#define yyget_lineno sc_get_lineno
#endif

#ifdef yyset_lineno
#define sc_set_lineno_ALREADY_DEFINED
#else
#define yyset_lineno sc_set_lineno
#endif

#ifdef yyget_column
#define sc_get_column_ALREADY_DEFINED
#else
#define yyget_column sc_get_column
#endif

#ifdef yyset_column
#define sc_set_column_ALREADY_DEFINED
#else
#define yyset_column sc_set_column
#endif

#ifdef yywrap
#define sc_wrap_ALREADY_DEFINED
#else
#define yywrap sc_wrap
#endif

#ifdef yyalloc
#define sc_alloc_ALREADY_DEFINED
#else
#define yyalloc sc_alloc
#endif

#ifdef yyrealloc
#define sc_realloc_ALREADY_DEFINED
#else
#define yyrealloc sc_realloc
#endif

#ifdef yyfree
#define sc_free_ALREADY_DEFINED
#else
#define yyfree sc_free
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin , yyscanner )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart ( FILE *input_file , yyscan_t yyscanner );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size , yyscan_t yyscanner );
void yy_delete_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yy_flush_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
void yypop_buffer_state ( yyscan_t yyscanner );

static void yyensure_buffer_stack ( yyscan_t yyscanner );
static void yy_load_buffer_state ( yyscan_t yyscanner );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file , yyscan_t yyscanner );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER , yyscanner)

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len , yyscan_t yyscanner );

void *yyalloc ( yy_size_t , yyscan_t yyscanner );
void *yyrealloc ( void *, yy_size_t , yyscan_t yyscanner );
void yyfree ( void * , yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define sc_wrap(yyscanner) (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state ( yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  , yyscan_t yyscanner);
static int yy_get_next_buffer ( yyscan_t yyscanner );
static void yynoreturn yy_fatal_error ( const char* msg , yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;
#define YY_NUM_RULES 71
#define YY_END_OF_BUFFER 72
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[112] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   72,   70,
        1,    2,   60,   14,   53,   59,   54,    9,   61,   62,
       50,   47,   67,   48,   52,   49,   22,   69,   68,   57,
       44,   58,   45,   55,   25,   65,   66,   51,   63,   46,
       64,   56,   47,   52,   13,   12,   11,   18,   17,   16,
        8,    7,    8,    1,   40,   23,   43,   35,   33,   34,
       21,    5,    4,   36,   19,   22,    0,    0,   38,    0,
        0,    0,   41,   39,   42,   24,   25,   37,    0,    3,
       33,   21,   10,   15,    6,   23,    0,    4,   19,    0,
        0,   20,   30,    0,   31,    0,    0,   32,    0,    0,

        0,   21,    0,   19,   26,   27,   29,   28,    0,   21,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    6,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   26,   26,   27,   27,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       28,    1,   29,   30,   26,    1,   26,   26,   26,   27,

       27,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   31,   32,   33,   34,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[35] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[117] =
    {   0,
        0,   22,   33,   34,   36,   41,   37,   42,  152,  153,
      149,  153,  128,  153,  153,  153,   21,  153,  153,  153,
       38,  127,  153,  126,  129,   39,   37,   48,  153,  124,
      123,  122,  153,  153,   47,  153,  153,  121,  153,  153,
      153,  153,   55,   60,  153,  153,  133,  153,  153,  136,
      153,  153,  123,  137,  153,   54,  153,  153,  153,  153,
       41,  153,    0,  153,   48,   66,   70,   57,  153,   67,
      116,   68,  153,  153,  153,  153,   81,  153,  125,  153,
      124,   91,  153,  153,  153,   74,   97,    0,   77,   98,
      107,  105,  153,  103,  153,  102,  100,  153,   87,  111,

       85,   80,   79,   78,  153,  153,  153,  153,   99,  102,
      153,  129,  131,  133,  135,   61
    } ;

static const flex_int16_t yy_def[117] =
    {   0,
      111,    1,  112,  112,  113,  113,  114,  114,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  115,  115,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  116,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  115,  111,
      115,  115,  111,  111,  111,  111,  111,  116,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  115,

      111,  111,  111,  111,  111,  111,  111,  111,  115,  115,
        0,  111,  111,  111,  111,  111
    } ;

static const flex_int16_t yy_nxt[188] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   35,   36,   37,   38,
       39,   40,   41,   42,   43,   46,   46,   44,   49,   52,
       50,   47,   47,   49,   52,   50,   56,   56,   53,   57,
       62,   68,   65,   53,   66,   63,   76,   80,   61,   58,
       64,   88,   80,   67,   77,   89,   69,   87,   70,   71,
       72,   86,   77,   77,   90,   93,   81,   82,   94,   86,
       86,   65,   91,   66,   91,   95,   98,   92,   96,   99,
       76,   86,   67,   80,   89,  104,  104,  102,   77,   86,

       86,   80,  102,   90,   80,  108,   77,   77,   82,  101,
      103,  101,  103,   80,  102,  104,  110,  100,  107,  110,
      106,  105,   92,  109,   92,  109,   80,   80,  110,   45,
       45,   48,   48,   51,   51,   79,   79,   97,   54,   85,
       84,   83,   78,   75,   74,   73,   61,   60,   59,   55,
       54,  111,    9,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111
    } ;

static const flex_int16_t yy_chk[188] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    2,    3,    4,    2,    5,    7,
        5,    3,    4,    6,    8,    6,   17,   17,    7,   21,
       26,   28,   27,    8,   27,   26,   35,   43,   61,   21,
       26,  116,   44,   27,   35,   65,   28,   61,   28,   28,
       28,   56,   35,   35,   65,   68,   43,   44,   68,   56,
       56,   66,   67,   66,   67,   70,   72,   67,   70,   72,
       77,   86,   66,   82,   89,  104,  103,  102,   77,   86,

       86,  109,  101,   89,  110,   99,   77,   77,   82,   87,
       90,   87,   90,  100,   87,   90,  109,   82,   97,  110,
       96,   94,   92,  100,   91,  100,   81,   79,  100,  112,
      112,  113,  113,  114,  114,  115,  115,   71,   54,   53,
       50,   47,   38,   32,   31,   30,   25,   24,   22,   13,
       11,    9,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[72] =
    {   0,
0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,     };

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "snocone.l"
/*
 * snocone.l — Snocone language Flex lexer  (GOAL-SNOCONE-LANG-SPACE LS-3.a)
 *
 * Andrew Koenig .sc operator set minus &&, ||, % plus CONCAT synthetic.
 * Commit identity: LCherryholmes / lcherryh@yahoo.com
 */
#define YY_NO_INPUT 1
#line 15 "snocone.l"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "snocone_lex2.h"

static int  classify_keyword(const char *s);
static void push_token_impl(ScTokenBuf *buf, int kind, const char *text, int line);
static int  can_start_expr_kind(int kind);
static void update_prev(LexerState *st, int kind);
static void maybe_emit_concat(LexerState *st, int next_can_start, int lineno);
static void push_call_depth(LexerState *st);
static int  pop_call_depth(LexerState *st);

#define TOK(kind) \
    do { \
        maybe_emit_concat(yyextra, can_start_expr_kind(kind), yylineno); \
        push_token_impl(yyextra->buf, (kind), yytext, yylineno); \
        update_prev(yyextra, (kind)); \
        yyextra->whitespace_seen = 0; \
    } while(0)

#line 765 "snocone.lex.c"

#line 767 "snocone.lex.c"

#define INITIAL 0
#define IN_SQ 1
#define IN_DQ 2
#define IN_BLOCK_COMMENT 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#define YY_EXTRA_TYPE LexerState *

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    }; /* end struct yyguts_t */

static int yy_init_globals ( yyscan_t yyscanner );

int yylex_init (yyscan_t* scanner);

int yylex_init_extra ( YY_EXTRA_TYPE user_defined, yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( yyscan_t yyscanner );

int yyget_debug ( yyscan_t yyscanner );

void yyset_debug ( int debug_flag , yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra ( yyscan_t yyscanner );

void yyset_extra ( YY_EXTRA_TYPE user_defined , yyscan_t yyscanner );

FILE *yyget_in ( yyscan_t yyscanner );

void yyset_in  ( FILE * _in_str , yyscan_t yyscanner );

FILE *yyget_out ( yyscan_t yyscanner );

void yyset_out  ( FILE * _out_str , yyscan_t yyscanner );

			int yyget_leng ( yyscan_t yyscanner );

char *yyget_text ( yyscan_t yyscanner );

int yyget_lineno ( yyscan_t yyscanner );

void yyset_lineno ( int _line_number , yyscan_t yyscanner );

int yyget_column  ( yyscan_t yyscanner );

void yyset_column ( int _column_no , yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( yyscan_t yyscanner );
#else
extern int yywrap ( yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int , yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * , yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( yyscan_t yyscanner );
#else
static int input ( yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (yyscan_t yyscanner);

#define YY_DECL int yylex (yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
		}

		yy_load_buffer_state( yyscanner );
		}

	{
#line 47 "snocone.l"


#line 1032 "snocone.lex.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 112 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 153 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 49 "snocone.l"
{ yyextra->whitespace_seen = 1; }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 50 "snocone.l"
{ yyextra->whitespace_seen = 1; }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 51 "snocone.l"
{ yyextra->whitespace_seen = 1; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 52 "snocone.l"
{ yyextra->whitespace_seen = 1; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 53 "snocone.l"
{ BEGIN(IN_BLOCK_COMMENT); yyextra->whitespace_seen = 1; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 54 "snocone.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 55 "snocone.l"
{ /* absorbed */ }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 56 "snocone.l"
{ /* absorbed */ }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 58 "snocone.l"
{ BEGIN(IN_SQ); sc_strlit_begin(yyextra, '\'', yylineno); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 59 "snocone.l"
{ sc_strlit_append_char(yyextra, '\''); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 60 "snocone.l"
{
    BEGIN(INITIAL);
    int ln = yyextra->strlit_start_line;
    char *s = sc_strlit_end(yyextra);
    maybe_emit_concat(yyextra, 1, ln);
    push_token_impl(yyextra->buf, SC2_STRING, s, ln);
    free(s);
    update_prev(yyextra, SC2_STRING);
    yyextra->whitespace_seen = 0;
}
	YY_BREAK
case 12:
/* rule 12 can match eol */
YY_RULE_SETUP
#line 70 "snocone.l"
{ sc_strlit_append_char(yyextra, '\n'); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 71 "snocone.l"
{ sc_strlit_append_char(yyextra, yytext[0]); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 73 "snocone.l"
{ BEGIN(IN_DQ); sc_strlit_begin(yyextra, '"', yylineno); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 74 "snocone.l"
{ sc_strlit_append_char(yyextra, '"'); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 75 "snocone.l"
{
    BEGIN(INITIAL);
    int ln = yyextra->strlit_start_line;
    char *s = sc_strlit_end(yyextra);
    maybe_emit_concat(yyextra, 1, ln);
    push_token_impl(yyextra->buf, SC2_STRING, s, ln);
    free(s);
    update_prev(yyextra, SC2_STRING);
    yyextra->whitespace_seen = 0;
}
	YY_BREAK
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 85 "snocone.l"
{ sc_strlit_append_char(yyextra, '\n'); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 86 "snocone.l"
{ sc_strlit_append_char(yyextra, yytext[0]); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 88 "snocone.l"
{ TOK(SC2_REAL); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 89 "snocone.l"
{ TOK(SC2_REAL); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 90 "snocone.l"
{ TOK(SC2_REAL); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 91 "snocone.l"
{ TOK(SC2_INTEGER); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 93 "snocone.l"
{ TOK(SC2_KEYWORD_NAME); }
	YY_BREAK
case 24:
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
yyg->yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 95 "snocone.l"
{
    char *name = strdup(yytext);

    maybe_emit_concat(yyextra, 1, yylineno);
    push_token_impl(yyextra->buf, SC2_IDENT_LPAREN_NOSP, name, yylineno);
    free(name);
    push_call_depth(yyextra);
    update_prev(yyextra, SC2_IDENT_LPAREN_NOSP);
    yyextra->whitespace_seen = 0;
    yyextra->absorb_next_lparen = 1;  /* next '(' is the call-open, absorb silently */
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 106 "snocone.l"
{ TOK(classify_keyword(yytext)); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 108 "snocone.l"
{ TOK(SC2_STR_NE); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 109 "snocone.l"
{ TOK(SC2_STR_LE); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 110 "snocone.l"
{ TOK(SC2_STR_GE); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 111 "snocone.l"
{ TOK(SC2_STR_EQ); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 112 "snocone.l"
{ TOK(SC2_STR_DIFFER); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 113 "snocone.l"
{ TOK(SC2_STR_LT); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 114 "snocone.l"
{ TOK(SC2_STR_GT); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 115 "snocone.l"
{ TOK(SC2_PLUS_ASSIGN); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 116 "snocone.l"
{ TOK(SC2_MINUS_ASSIGN); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 117 "snocone.l"
{ TOK(SC2_STAR_ASSIGN); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 118 "snocone.l"
{ TOK(SC2_SLASH_ASSIGN); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 119 "snocone.l"
{ TOK(SC2_CARET_ASSIGN); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 120 "snocone.l"
{ TOK(SC2_STR_IDENT); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 121 "snocone.l"
{ TOK(SC2_EQ); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 122 "snocone.l"
{ TOK(SC2_NE); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 123 "snocone.l"
{ TOK(SC2_LE); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 124 "snocone.l"
{ TOK(SC2_GE); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 125 "snocone.l"
{ TOK(SC2_CARET); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 126 "snocone.l"
{ TOK(SC2_ASSIGN); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 127 "snocone.l"
{ TOK(SC2_QUESTION); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 128 "snocone.l"
{ TOK(SC2_PIPE); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 129 "snocone.l"
{ TOK(SC2_PLUS); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 130 "snocone.l"
{ TOK(SC2_MINUS); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 131 "snocone.l"
{ TOK(SC2_SLASH); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 132 "snocone.l"
{ TOK(SC2_STAR); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 133 "snocone.l"
{ TOK(SC2_CARET); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 134 "snocone.l"
{ TOK(SC2_PERIOD); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 135 "snocone.l"
{ TOK(SC2_DOLLAR); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 136 "snocone.l"
{ TOK(SC2_AMPERSAND); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 137 "snocone.l"
{ TOK(SC2_AT); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 138 "snocone.l"
{ TOK(SC2_TILDE); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 139 "snocone.l"
{ TOK(SC2_LT); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 140 "snocone.l"
{ TOK(SC2_GT); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 141 "snocone.l"
{ TOK(SC2_PERCENT); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 142 "snocone.l"
{ TOK(SC2_BANG_EXPONENT); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 144 "snocone.l"
{
    if (yyextra->absorb_next_lparen) {
        /* This '(' is the call-open paren implied by IDENT_LPAREN_NOSP.
         * Do NOT emit a LPAREN token — the grammar knows from the
         * IDENT_LPAREN_NOSP token that a '(' was consumed.
         * DO increment paren_depth so RPAREN tracking works. */
        yyextra->absorb_next_lparen = 0;
        yyextra->paren_depth++;
        /* prev stays PT_OPEN (set by update_prev for IDENT_LPAREN_NOSP) */
    } else {
        maybe_emit_concat(yyextra, 1, yylineno);
        push_token_impl(yyextra->buf, SC2_LPAREN, yytext, yylineno);
        yyextra->paren_depth++;
        update_prev(yyextra, SC2_LPAREN);
        yyextra->whitespace_seen = 0;
    }
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 161 "snocone.l"
{
    int is_call = pop_call_depth(yyextra);
    (void)is_call;
    maybe_emit_concat(yyextra, 0, yylineno);
    push_token_impl(yyextra->buf, SC2_RPAREN, yytext, yylineno);
    if (yyextra->paren_depth > 0) yyextra->paren_depth--;
    update_prev(yyextra, SC2_RPAREN);
    yyextra->whitespace_seen = 0;
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 170 "snocone.l"
{ TOK(SC2_LBRACE); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 171 "snocone.l"
{ TOK(SC2_RBRACE); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 172 "snocone.l"
{ TOK(SC2_LBRACKET); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 173 "snocone.l"
{ TOK(SC2_RBRACKET); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 174 "snocone.l"
{ TOK(SC2_COMMA); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 175 "snocone.l"
{ TOK(SC2_SEMICOLON); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 176 "snocone.l"
{ TOK(SC2_COLON); }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(IN_SQ):
case YY_STATE_EOF(IN_DQ):
case YY_STATE_EOF(IN_BLOCK_COMMENT):
#line 178 "snocone.l"
{
    push_token_impl(yyextra->buf, SC2_EOF, "", yylineno);
    yyterminate();
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 183 "snocone.l"
{
    push_token_impl(yyextra->buf, SC2_UNKNOWN, yytext, yylineno);
    yyextra->whitespace_seen = 0;
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 188 "snocone.l"
ECHO;
	YY_BREAK
#line 1530 "snocone.lex.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap( yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  , yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size , yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 112 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	char *yy_cp = yyg->yy_c_buf_p;

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 112 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 111);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr);
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin , yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file , yyscanner);
	yy_load_buffer_state( yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file , yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf , yyscanner );

	yyfree( (void *) b , yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer( b , yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER , yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b , yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) , yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n , yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n , yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void yyset_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* Accessor methods for yylval and yylloc */

/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */
int yylex_init(yyscan_t* ptr_yy_globals)
{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */
int yylex_init_extra( YY_EXTRA_TYPE yy_user_defined, yyscan_t* ptr_yy_globals )
{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    yyset_extra (yy_user_defined, *ptr_yy_globals);

    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = NULL;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = NULL;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER , yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack , yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree( yyg->yy_start_stack , yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 188 "snocone.l"


typedef struct { const char *word; int kind; } KwEntry;
static const KwEntry KW_TABLE[] = {
    { "if",       SC2_KW_IF       },
    { "else",     SC2_KW_ELSE     },
    { "while",    SC2_KW_WHILE    },
    { "do",       SC2_KW_DO       },
    { "until",    SC2_KW_UNTIL    },
    { "for",      SC2_KW_FOR      },
    { "switch",   SC2_KW_SWITCH   },
    { "case",     SC2_KW_CASE     },
    { "default",  SC2_KW_DEFAULT  },
    { "break",    SC2_KW_BREAK    },
    { "continue", SC2_KW_CONTINUE },
    { "goto",     SC2_KW_GOTO     },
    { "function", SC2_KW_FUNCTION },
    { "return",   SC2_KW_RETURN   },
    { "freturn",  SC2_KW_FRETURN  },
    { "nreturn",  SC2_KW_NRETURN  },
    { "struct",   SC2_KW_STRUCT   },
    { NULL,       SC2_IDENT       }
};

static int classify_keyword(const char *s) {
    for (const KwEntry *e = KW_TABLE; e->word; e++)
        if (strcmp(s, e->word) == 0) return e->kind;
    return SC2_IDENT;
}

static int can_start_expr_kind(int kind) {
    /* Only tokens that are UNAMBIGUOUSLY the start of a new operand trigger
     * CONCAT emission.  Tokens that double as binary operators (?, &, +, -, *,
     * ., $) do NOT trigger CONCAT — in a post-value position they are binary.
     * The grammar handles precedence from there. */
    switch (kind) {
    case SC2_IDENT:
    case SC2_IDENT_LPAREN_NOSP:
    case SC2_INTEGER:
    case SC2_REAL:
    case SC2_STRING:
    case SC2_KEYWORD_NAME:
    case SC2_LPAREN:
    case SC2_LBRACKET:
    /* Unambiguously unary — have no binary role in the operator table */
    case SC2_TILDE:
    case SC2_AT:
        return 1;
    default:
        return 0;
    }
}

static void update_prev(LexerState *st, int kind) {
    switch (kind) {
    case SC2_IDENT: case SC2_INTEGER: case SC2_REAL: case SC2_STRING:
    case SC2_KEYWORD_NAME: case SC2_RPAREN: case SC2_RBRACKET:
        st->prev = PT_VALUE; break;
    case SC2_IDENT_LPAREN_NOSP:
        st->prev = PT_OPEN; break;
    case SC2_LPAREN: case SC2_LBRACE: case SC2_LBRACKET:
        st->prev = PT_OPEN; break;
    case SC2_COMMA: case SC2_SEMICOLON: case SC2_COLON: case SC2_RBRACE:
        st->prev = PT_NONE; break;
    case SC2_AMPERSAND: case SC2_AT: case SC2_TILDE:
        st->prev = PT_UNARY_PREFIX; break;
    case SC2_KW_IF: case SC2_KW_WHILE: case SC2_KW_FOR: case SC2_KW_DO:
    case SC2_KW_UNTIL: case SC2_KW_SWITCH: case SC2_KW_CASE:
    case SC2_KW_DEFAULT: case SC2_KW_FUNCTION: case SC2_KW_ELSE:
    case SC2_KW_STRUCT:
        st->prev = PT_KW_BLOCK_OPENER; break;
    case SC2_KW_BREAK: case SC2_KW_CONTINUE: case SC2_KW_GOTO:
    case SC2_KW_RETURN: case SC2_KW_FRETURN: case SC2_KW_NRETURN:
        st->prev = PT_KW_LOOPCTRL; break;
    default:
        st->prev = PT_BINOP; break;
    }
}

static void maybe_emit_concat(LexerState *st, int next_can_start, int lineno) {
    if (st->prev == PT_VALUE && next_can_start && st->whitespace_seen)
        push_token_impl(st->buf, SC2_CONCAT, "", lineno);
}

static void push_call_depth(LexerState *st) {
    /* The '(' is NOT yet consumed (trailing context) so paren_depth has not
     * been incremented yet.  Record paren_depth+1 as the target depth — that
     * is the depth the call's RPAREN will see when it arrives. */
    int target = st->paren_depth + 1;
    if (st->call_stack_top < SC2_MAX_CALL_DEPTH - 1)
        st->call_stack[++st->call_stack_top] = target;
}

static int pop_call_depth(LexerState *st) {
    if (st->call_stack_top >= 0
            && st->call_stack[st->call_stack_top] == st->paren_depth) {
        st->call_stack_top--;
        return 1;
    }
    return 0;
}

static void push_token_impl(ScTokenBuf *buf, int kind, const char *text, int line) {
    if (buf->count >= buf->capacity) {
        buf->capacity = buf->capacity ? buf->capacity * 2 : 64;
        buf->tokens = realloc(buf->tokens, buf->capacity * sizeof(ScToken2));
    }
    ScToken2 *t = &buf->tokens[buf->count++];
    t->kind = kind;
    t->text = strdup(text);
    t->line = line;
}

void sc_strlit_begin(LexerState *st, char quote, int line) {
    st->strlit_quote = quote;
    st->strlit_start_line = line;
    st->strlit_len = 0;
    st->strlit_cap = 64;
    st->strlit_buf = malloc(st->strlit_cap);
    st->strlit_buf[0] = '\0';
}

void sc_strlit_append_char(LexerState *st, char c) {
    if (st->strlit_len + 2 >= st->strlit_cap) {
        st->strlit_cap *= 2;
        st->strlit_buf = realloc(st->strlit_buf, st->strlit_cap);
    }
    st->strlit_buf[st->strlit_len++] = c;
    st->strlit_buf[st->strlit_len] = '\0';
}

void sc_strlit_append(LexerState *st, char c) { sc_strlit_append_char(st, c); }

char *sc_strlit_end(LexerState *st) { return strdup(st->strlit_buf); }

ScTokenBuf snocone_lex2(const char *source) {
    LexerState st;
    memset(&st, 0, sizeof(st));
    st.prev = PT_NONE;
    st.call_stack_top = -1;

    ScTokenBuf buf;
    memset(&buf, 0, sizeof(buf));
    st.buf = &buf;

    yyscan_t scanner;
    sc_lex_init_extra(&st, &scanner);
    YY_BUFFER_STATE ybuf = sc__scan_string(source, scanner);
    sc_lex(scanner);
    sc__delete_buffer(ybuf, scanner);
    sc_lex_destroy(scanner);

    if (st.strlit_buf) free(st.strlit_buf);
    return buf;
}

void sc_token_buf_free(ScTokenBuf *buf) {
    for (int i = 0; i < buf->count; i++) free(buf->tokens[i].text);
    free(buf->tokens);
    buf->tokens = NULL; buf->count = 0; buf->capacity = 0;
}

const char *sc2_kind_name(int kind) {
    switch (kind) {
    case SC2_INTEGER:           return "INTEGER";
    case SC2_REAL:              return "REAL";
    case SC2_STRING:            return "STRING";
    case SC2_IDENT:             return "IDENT";
    case SC2_IDENT_LPAREN_NOSP: return "IDENT_LPAREN_NOSP";
    case SC2_KEYWORD_NAME:      return "KEYWORD_NAME";
    case SC2_CONCAT:            return "CONCAT";
    case SC2_ASSIGN:            return "ASSIGN";
    case SC2_QUESTION:          return "QUESTION";
    case SC2_PIPE:              return "PIPE";
    case SC2_EQ:                return "EQ";
    case SC2_NE:                return "NE";
    case SC2_LT:                return "LT";
    case SC2_GT:                return "GT";
    case SC2_LE:                return "LE";
    case SC2_GE:                return "GE";
    case SC2_STR_IDENT:         return "STR_IDENT";
    case SC2_STR_DIFFER:        return "STR_DIFFER";
    case SC2_STR_LT:            return "STR_LT";
    case SC2_STR_GT:            return "STR_GT";
    case SC2_STR_LE:            return "STR_LE";
    case SC2_STR_GE:            return "STR_GE";
    case SC2_STR_EQ:            return "STR_EQ";
    case SC2_STR_NE:            return "STR_NE";
    case SC2_PLUS:              return "PLUS";
    case SC2_MINUS:             return "MINUS";
    case SC2_SLASH:             return "SLASH";
    case SC2_STAR:              return "STAR";
    case SC2_PERCENT:           return "PERCENT";
    case SC2_CARET:             return "CARET";
    case SC2_BANG_EXPONENT:     return "BANG_EXPONENT";
    case SC2_PERIOD:            return "PERIOD";
    case SC2_DOLLAR:            return "DOLLAR";
    case SC2_AT:                return "AT";
    case SC2_TILDE:             return "TILDE";
    case SC2_AMPERSAND:         return "AMPERSAND";
    case SC2_PLUS_ASSIGN:       return "PLUS_ASSIGN";
    case SC2_MINUS_ASSIGN:      return "MINUS_ASSIGN";
    case SC2_STAR_ASSIGN:       return "STAR_ASSIGN";
    case SC2_SLASH_ASSIGN:      return "SLASH_ASSIGN";
    case SC2_CARET_ASSIGN:      return "CARET_ASSIGN";
    case SC2_LPAREN:            return "LPAREN";
    case SC2_RPAREN:            return "RPAREN";
    case SC2_LBRACE:            return "LBRACE";
    case SC2_RBRACE:            return "RBRACE";
    case SC2_LBRACKET:          return "LBRACKET";
    case SC2_RBRACKET:          return "RBRACKET";
    case SC2_COMMA:             return "COMMA";
    case SC2_SEMICOLON:         return "SEMICOLON";
    case SC2_COLON:             return "COLON";
    case SC2_KW_IF:             return "KW_IF";
    case SC2_KW_ELSE:           return "KW_ELSE";
    case SC2_KW_WHILE:          return "KW_WHILE";
    case SC2_KW_DO:             return "KW_DO";
    case SC2_KW_UNTIL:          return "KW_UNTIL";
    case SC2_KW_FOR:            return "KW_FOR";
    case SC2_KW_SWITCH:         return "KW_SWITCH";
    case SC2_KW_CASE:           return "KW_CASE";
    case SC2_KW_DEFAULT:        return "KW_DEFAULT";
    case SC2_KW_BREAK:          return "KW_BREAK";
    case SC2_KW_CONTINUE:       return "KW_CONTINUE";
    case SC2_KW_GOTO:           return "KW_GOTO";
    case SC2_KW_FUNCTION:       return "KW_FUNCTION";
    case SC2_KW_RETURN:         return "KW_RETURN";
    case SC2_KW_FRETURN:        return "KW_FRETURN";
    case SC2_KW_NRETURN:        return "KW_NRETURN";
    case SC2_KW_STRUCT:         return "KW_STRUCT";
    case SC2_EOF:               return "EOF";
    case SC2_UNKNOWN:           return "UNKNOWN";
    default:                    return "???";
    }
}

