#line 2 "snocone.lex.c"

#line 4 "snocone.lex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define sc__create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer sc__create_buffer
#endif

#ifdef yy_delete_buffer
#define sc__delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer sc__delete_buffer
#endif

#ifdef yy_scan_buffer
#define sc__scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer sc__scan_buffer
#endif

#ifdef yy_scan_string
#define sc__scan_string_ALREADY_DEFINED
#else
#define yy_scan_string sc__scan_string
#endif

#ifdef yy_scan_bytes
#define sc__scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes sc__scan_bytes
#endif

#ifdef yy_init_buffer
#define sc__init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer sc__init_buffer
#endif

#ifdef yy_flush_buffer
#define sc__flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer sc__flush_buffer
#endif

#ifdef yy_load_buffer_state
#define sc__load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state sc__load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define sc__switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer sc__switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define sc_push_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state sc_push_buffer_state
#endif

#ifdef yypop_buffer_state
#define sc_pop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state sc_pop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define sc_ensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack sc_ensure_buffer_stack
#endif

#ifdef yylex
#define sc_lex_ALREADY_DEFINED
#else
#define yylex sc_lex
#endif

#ifdef yyrestart
#define sc_restart_ALREADY_DEFINED
#else
#define yyrestart sc_restart
#endif

#ifdef yylex_init
#define sc_lex_init_ALREADY_DEFINED
#else
#define yylex_init sc_lex_init
#endif

#ifdef yylex_init_extra
#define sc_lex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra sc_lex_init_extra
#endif

#ifdef yylex_destroy
#define sc_lex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy sc_lex_destroy
#endif

#ifdef yyget_debug
#define sc_get_debug_ALREADY_DEFINED
#else
#define yyget_debug sc_get_debug
#endif

#ifdef yyset_debug
#define sc_set_debug_ALREADY_DEFINED
#else
#define yyset_debug sc_set_debug
#endif

#ifdef yyget_extra
#define sc_get_extra_ALREADY_DEFINED
#else
#define yyget_extra sc_get_extra
#endif

#ifdef yyset_extra
#define sc_set_extra_ALREADY_DEFINED
#else
#define yyset_extra sc_set_extra
#endif

#ifdef yyget_in
#define sc_get_in_ALREADY_DEFINED
#else
#define yyget_in sc_get_in
#endif

#ifdef yyset_in
#define sc_set_in_ALREADY_DEFINED
#else
#define yyset_in sc_set_in
#endif

#ifdef yyget_out
#define sc_get_out_ALREADY_DEFINED
#else
#define yyget_out sc_get_out
#endif

#ifdef yyset_out
#define sc_set_out_ALREADY_DEFINED
#else
#define yyset_out sc_set_out
#endif

#ifdef yyget_leng
#define sc_get_leng_ALREADY_DEFINED
#else
#define yyget_leng sc_get_leng
#endif

#ifdef yyget_text
#define sc_get_text_ALREADY_DEFINED
#else
#define yyget_text sc_get_text
#endif

#ifdef yyget_lineno
#define sc_get_lineno_ALREADY_DEFINED
#else
#define yyget_lineno sc_get_lineno
#endif

#ifdef yyset_lineno
#define sc_set_lineno_ALREADY_DEFINED
#else
#define yyset_lineno sc_set_lineno
#endif

#ifdef yyget_column
#define sc_get_column_ALREADY_DEFINED
#else
#define yyget_column sc_get_column
#endif

#ifdef yyset_column
#define sc_set_column_ALREADY_DEFINED
#else
#define yyset_column sc_set_column
#endif

#ifdef yywrap
#define sc_wrap_ALREADY_DEFINED
#else
#define yywrap sc_wrap
#endif

#ifdef yyalloc
#define sc_alloc_ALREADY_DEFINED
#else
#define yyalloc sc_alloc
#endif

#ifdef yyrealloc
#define sc_realloc_ALREADY_DEFINED
#else
#define yyrealloc sc_realloc
#endif

#ifdef yyfree
#define sc_free_ALREADY_DEFINED
#else
#define yyfree sc_free
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin , yyscanner )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart ( FILE *input_file , yyscan_t yyscanner );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size , yyscan_t yyscanner );
void yy_delete_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yy_flush_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
void yypop_buffer_state ( yyscan_t yyscanner );

static void yyensure_buffer_stack ( yyscan_t yyscanner );
static void yy_load_buffer_state ( yyscan_t yyscanner );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file , yyscan_t yyscanner );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER , yyscanner)

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len , yyscan_t yyscanner );

void *yyalloc ( yy_size_t , yyscan_t yyscanner );
void *yyrealloc ( void *, yy_size_t , yyscan_t yyscanner );
void yyfree ( void * , yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define sc_wrap(yyscanner) (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state ( yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  , yyscan_t yyscanner);
static int yy_get_next_buffer ( yyscan_t yyscanner );
static void yynoreturn yy_fatal_error ( const char* msg , yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;
#define YY_NUM_RULES 89
#define YY_END_OF_BUFFER 90
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[321] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   90,    1,   89,   88,   18,   18,   73,    8,
       83,   81,   78,   87,    7,   56,   57,   76,   74,   60,
       75,   82,   77,   70,   64,   61,   85,   86,   79,   66,
       58,   59,   72,   62,   84,   63,   80,   12,   11,   10,
       16,   15,   14,    6,    5,    6,   18,   18,    0,    0,
        0,    0,    0,   57,    0,    0,   60,    0,    0,    0,
       64,   61,    0,   20,    0,    0,    0,   59,    0,   62,
        0,   63,    0,   18,   18,   17,   56,   56,   71,   39,
       37,   60,   60,   38,   69,    3,    2,   40,   67,   70,

        0,   65,   66,   58,   58,   41,   62,   62,    9,   13,
        4,   44,   44,    0,   55,   55,   49,   49,   53,   53,
       51,   51,   47,   47,    0,   45,   45,   46,   46,   50,
       50,   48,   48,    0,    0,    0,    0,    0,   35,   35,
        0,   19,   19,    0,   36,   36,    0,   21,   21,   52,
       52,   43,   43,   22,   22,   54,   54,   18,   18,   20,
       18,   18,   17,   56,   39,   39,   37,   37,   60,   38,
       38,    0,    2,   40,   40,   67,    0,    0,   68,   58,
       41,   41,   62,   44,   32,   32,   55,   49,   53,   51,
       47,   42,   42,   45,   46,   50,   48,    0,    0,   30,

       30,    0,    0,    0,    0,    0,   35,   33,   33,   19,
       31,   31,   36,   34,   34,   21,   52,   43,   22,   54,
       18,   18,   18,   19,   19,   18,   18,   18,   56,   39,
       37,   60,   38,    0,   69,   40,    0,   67,   58,   41,
       62,   44,   32,   55,   49,   53,   51,   47,   42,   45,
       46,   50,   48,   29,   29,    0,   30,   27,   27,    0,
        0,   28,   28,    0,   35,   33,   19,   31,   36,   34,
       21,   52,   43,   22,   54,   18,   18,   18,   19,   18,
       18,   39,   37,   38,   40,   41,   32,   42,   29,   24,
       24,   30,   27,   25,   25,   23,   23,   28,   26,   26,

       33,   31,   34,   18,   18,   18,   19,   29,   24,   27,
       25,   23,   28,   26,   18,   24,   25,   23,   26,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   27,   27,   28,   28,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       29,    1,   30,   31,   27,    1,   27,   27,   27,   28,

       28,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   32,   33,   34,   35,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[36] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[327] =
    {   0,
        0,    0,    0,    0,    0,    0,   33,   34,   35,   36,
       39,   42,  301,  738,  738,  738,   54,   32,  738,  738,
      738,  738,  738,   20,  738,   48,  738,   41,  249,   79,
      236,  233,   77,   74,  738,  738,  738,  738,  738,   85,
       95,  738,  220,  103,  738,  738,  738,  738,  738,  210,
      738,  738,  197,  738,  738,  157,    0,   93,  106,  112,
      114,  116,  118,  738,  120,  122,  124,  128,  132,  134,
      124,  738,  136,  138,  147,  150,  152,  738,  160,  162,
      164,  738,  166,  169,  171,  157,  175,  177,  738,  179,
      184,  186,  193,  195,   64,  738,    0,  197,   75,  184,

      190,  738,  194,  212,  214,  216,  221,  223,  738,  738,
      738,  227,  230,  232,  236,  239,  243,  246,  248,  252,
      255,  259,  262,  265,  268,  272,  275,  278,  281,  283,
      285,  288,  291,  170,  294,  188,  137,  280,  304,  307,
      309,  311,  313,  315,  317,  320,  323,  326,  329,  333,
      336,  338,  342,  345,  349,  352,  355,  358,  362,  365,
      368,  372,  354,  375,  381,  388,  390,  392,  394,  396,
      398,  394,    0,  401,  414,  208,  404,  139,  137,  419,
      422,  424,  427,  430,  432,  434,  437,  440,  442,  444,
      447,  450,  452,  454,  456,  458,  460,  462,  122,  465,

      468,  470,  112,   91,  472,   81,  474,  476,  478,  481,
      484,  486,  488,  491,  494,  496,  499,  502,  504,  507,
      510,  512,  514,  516,  519,  521,  523,  525,  527,  529,
      535,  537,  539,   80,   54,  541,   46,   40,  545,  547,
      549,  551,  553,  555,  557,  559,  561,  563,  565,  567,
      569,  571,  573,  575,  577,  579,  581,  583,  585,  587,
      590,  593,  595,  598,  601,  603,  605,  608,  611,  613,
      615,  617,  619,  621,  623,  625,  627,  629,  631,  633,
      635,  637,  639,  642,  645,  647,  649,  651,  653,  655,
      657,  659,  661,  663,  665,  667,  670,  673,  675,  678,

      683,  686,  688,  691,  694,  696,  698,  700,  702,  704,
      706,  708,  710,  712,  716,  718,  720,  722,  724,  738,
      727,  729,  731,  733,  735,   52
    } ;

static const flex_int16_t yy_def[327] =
    {   0,
      321,  321,  322,  322,  320,    5,  323,  323,  324,  324,
      325,  325,  320,  320,  320,  320,  320,   17,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,   17,   17,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,   17,   17,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  326,  320,  320,  320,

      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,   17,   17,  320,
       17,   17,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  326,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,

      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
       17,   17,   17,  320,  320,   17,   17,   17,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,   17,   17,   17,  320,   17,
       17,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,

      320,  320,  320,   17,   17,   17,  320,  320,  320,  320,
      320,  320,  320,  320,   17,  320,  320,  320,  320,    0,
      320,  320,  320,  320,  320,  320
    } ;

static const flex_int16_t yy_nxt[774] =
    {   0,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   16,   37,   16,   38,   39,   40,   40,   41,   42,
       43,   44,   45,   46,   47,   49,   49,   52,   52,   53,
       53,   55,   50,   50,   55,   84,   86,   86,   85,   87,
       88,   56,  173,   89,   56,   57,   58,   59,  238,   60,
       61,   62,   63,   90,  238,   64,   65,   66,   67,   68,
       69,   70,  235,   71,   72,   73,   74,   75,   76,   77,
       92,   93,   95,   78,   79,   80,   81,   82,   83,   96,
       99,  172,  100,  176,   97,  102,  104,  105,  235,   98,

      264,  101,  177,  103,  107,  108,   84,  112,  113,   85,
      261,  103,  103,  115,  116,  117,  118,  119,  120,  121,
      122,  123,  124,  126,  127,   92,   93,  134,  114,  128,
      129,  260,  125,  130,  131,  132,  133,  139,  140,  142,
      143,  256,   90,  135,   91,  136,  137,  138,  145,  146,
       94,  148,  149,  150,  151,  179,   98,  179,  141,  204,
      144,  152,  153,  107,  108,  154,  155,  156,  157,  147,
      158,  159,  161,  162,  111,  163,   87,   88,   87,   88,
      165,  166,  106,  163,  163,  167,  168,   92,   93,  198,
      164,  160,  199,  164,   92,   93,  170,  171,  174,  175,

       99,  110,  100,  178,  102,  178,  169,  202,  179,  169,
      203,  101,  103,  104,  105,  104,  105,  181,  182,  109,
      103,  103,  107,  108,  107,  108,  176,  180,  112,  113,
      180,  112,  113,  185,  186,  177,  183,  115,  116,  183,
      115,  116,  106,  184,  117,  118,  184,  117,  118,  119,
      120,   95,  187,  119,  120,  187,  121,  122,   94,  188,
      121,  122,  188,  123,  124,  189,  123,  124,  189,  192,
      193,   91,  190,  126,  127,  190,  126,  127,  191,  128,
      129,  191,  128,  129,  130,  131,  130,  131,  194,  132,
      133,  194,  132,  133,  195,  200,  201,  195,  196,  205,

      320,  196,  206,  320,  197,  139,  140,  197,  139,  140,
      208,  209,  142,  143,  142,  143,  211,  212,  145,  146,
      207,  145,  146,  207,  214,  215,  210,  148,  149,  210,
      148,  149,  320,  213,  150,  151,  213,  150,  151,  152,
      153,  320,  216,  152,  153,  216,  154,  155,  320,  217,
      154,  155,  217,  156,  157,  218,  156,  157,  218,  158,
      159,  320,  219,  221,  159,  219,  224,  225,  220,  161,
      162,  220,  163,  226,  162,  222,  229,   88,  223,  320,
      163,  163,  165,  166,  320,  227,  320,  144,  228,  165,
      166,  167,  168,  167,  168,  232,   93,  170,  171,  170,

      171,  230,  174,  175,  230,  231,  320,  234,  231,  234,
      320,  233,  235,  320,  233,  174,  175,  237,  320,  237,
      239,  105,  238,  181,  182,  181,  182,  236,  241,  108,
      236,  242,  113,  185,  186,  185,  186,  240,  244,  116,
      240,  245,  118,  246,  120,  247,  122,  243,  248,  124,
      243,  192,  193,  192,  193,  250,  127,  251,  129,  252,
      131,  253,  133,  254,  255,  249,  200,  201,  249,  200,
      201,  258,  259,  262,  263,  265,  140,  208,  209,  208,
      209,  257,  267,  143,  257,  211,  212,  211,  212,  269,
      146,  266,  214,  215,  266,  214,  215,  271,  149,  268,

      272,  151,  268,  273,  153,  274,  155,  270,  275,  157,
      270,  221,  159,  276,  159,  277,  278,  224,  225,  320,
      224,  225,  226,  162,  280,  278,  281,  162,  229,   88,
      282,  166,  279,  320,  160,  279,  283,  168,  232,   93,
      284,  171,  285,  175,  320,  160,  239,  105,  286,  182,
      241,  108,  242,  113,  287,  186,  244,  116,  245,  118,
      246,  120,  247,  122,  248,  124,  288,  193,  250,  127,
      251,  129,  252,  131,  253,  133,  254,  255,  254,  255,
      290,  291,  292,  201,  258,  259,  258,  259,  294,  295,
      289,  296,  297,  289,  262,  263,  262,  263,  293,  299,

      300,  293,  265,  140,  301,  209,  267,  143,  298,  302,
      212,  298,  269,  146,  303,  215,  271,  149,  272,  151,
      273,  153,  274,  155,  275,  157,  276,  159,  277,  278,
      304,  278,  307,  225,  280,  278,  281,  162,  282,  166,
      283,  168,  305,  284,  171,  306,  285,  175,  286,  182,
      287,  186,  288,  193,  308,  255,  290,  291,  290,  291,
      292,  201,  310,  259,  294,  295,  294,  295,  296,  297,
      309,  296,  297,  309,  313,  263,  299,  300,  311,  299,
      300,  311,  320,  312,  301,  209,  312,  302,  212,  303,
      215,  314,  304,  278,  314,  315,  278,  315,  278,  307,

      225,  308,  255,  316,  291,  310,  259,  317,  295,  318,
      297,  313,  263,  319,  300,  320,  160,  315,  278,  316,
      291,  317,  295,  318,  297,  319,  300,   14,   14,   15,
       15,   48,   48,   51,   51,   54,   54,   13,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320
    } ;

static const flex_int16_t yy_chk[774] =
    {   0,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    7,    8,    9,   10,    9,
       10,   11,    7,    8,   12,   18,   24,   24,   18,   26,
       26,   11,  326,   28,   12,   17,   17,   17,  238,   17,
       17,   17,   17,   28,  237,   17,   17,   17,   17,   17,
       17,   17,  235,   17,   17,   17,   17,   17,   17,   17,
       30,   30,   95,   17,   17,   17,   17,   17,   17,   33,
       34,   95,   34,   99,   33,   40,   41,   41,  234,   33,

      206,   34,   99,   40,   44,   44,   58,   59,   59,   58,
      204,   40,   40,   60,   60,   61,   61,   62,   62,   63,
       63,   65,   65,   66,   66,   67,   67,   71,   59,   68,
       68,  203,   65,   69,   69,   70,   70,   73,   73,   74,
       74,  199,   65,   71,   66,   71,   71,   71,   75,   75,
       68,   76,   76,   77,   77,  179,   70,  178,   73,  137,
       74,   79,   79,   80,   80,   81,   81,   83,   83,   75,
       84,   84,   85,   85,   56,   86,   87,   87,   88,   88,
       90,   90,   79,   86,   86,   91,   91,   92,   92,  134,
       88,   84,  134,   88,   93,   93,   94,   94,   98,   98,

      100,   53,  100,  101,  103,  101,   93,  136,  101,   93,
      136,  100,  103,  104,  104,  105,  105,  106,  106,   50,
      103,  103,  107,  107,  108,  108,  176,  105,  112,  112,
      105,  113,  113,  114,  114,  176,  108,  115,  115,  108,
      116,  116,   43,  113,  117,  117,  113,  118,  118,  119,
      119,   32,  116,  120,  120,  116,  121,  121,   31,  118,
      122,  122,  118,  123,  123,  120,  124,  124,  120,  125,
      125,   29,  122,  126,  126,  122,  127,  127,  124,  128,
      128,  124,  129,  129,  130,  130,  131,  131,  127,  132,
      132,  127,  133,  133,  129,  135,  135,  129,  131,  138,

       13,  131,  138,    0,  133,  139,  139,  133,  140,  140,
      141,  141,  142,  142,  143,  143,  144,  144,  145,  145,
      140,  146,  146,  140,  147,  147,  143,  148,  148,  143,
      149,  149,    0,  146,  150,  150,  146,  151,  151,  152,
      152,    0,  149,  153,  153,  149,  154,  154,    0,  151,
      155,  155,  151,  156,  156,  153,  157,  157,  153,  158,
      158,    0,  155,  159,  159,  155,  160,  160,  157,  161,
      161,  157,  163,  162,  162,  159,  164,  164,  159,    0,
      163,  163,  165,  165,    0,  162,    0,  160,  162,  166,
      166,  167,  167,  168,  168,  169,  169,  170,  170,  171,

      171,  166,  174,  174,  166,  168,    0,  172,  168,  172,
        0,  171,  172,    0,  171,  175,  175,  177,    0,  177,
      180,  180,  177,  181,  181,  182,  182,  175,  183,  183,
      175,  184,  184,  185,  185,  186,  186,  182,  187,  187,
      182,  188,  188,  189,  189,  190,  190,  186,  191,  191,
      186,  192,  192,  193,  193,  194,  194,  195,  195,  196,
      196,  197,  197,  198,  198,  193,  200,  200,  193,  201,
      201,  202,  202,  205,  205,  207,  207,  208,  208,  209,
      209,  201,  210,  210,  201,  211,  211,  212,  212,  213,
      213,  209,  214,  214,  209,  215,  215,  216,  216,  212,

      217,  217,  212,  218,  218,  219,  219,  215,  220,  220,
      215,  221,  221,  222,  222,  223,  223,  224,  224,    0,
      225,  225,  226,  226,  227,  227,  228,  228,  229,  229,
      230,  230,  225,    0,  222,  225,  231,  231,  232,  232,
      233,  233,  236,  236,    0,  227,  239,  239,  240,  240,
      241,  241,  242,  242,  243,  243,  244,  244,  245,  245,
      246,  246,  247,  247,  248,  248,  249,  249,  250,  250,
      251,  251,  252,  252,  253,  253,  254,  254,  255,  255,
      256,  256,  257,  257,  258,  258,  259,  259,  260,  260,
      255,  261,  261,  255,  262,  262,  263,  263,  259,  264,

      264,  259,  265,  265,  266,  266,  267,  267,  263,  268,
      268,  263,  269,  269,  270,  270,  271,  271,  272,  272,
      273,  273,  274,  274,  275,  275,  276,  276,  277,  277,
      278,  278,  279,  279,  280,  280,  281,  281,  282,  282,
      283,  283,  278,  284,  284,  278,  285,  285,  286,  286,
      287,  287,  288,  288,  289,  289,  290,  290,  291,  291,
      292,  292,  293,  293,  294,  294,  295,  295,  296,  296,
      291,  297,  297,  291,  298,  298,  299,  299,  295,  300,
      300,  295,    0,  297,  301,  301,  297,  302,  302,  303,
      303,  300,  304,  304,  300,  305,  305,  306,  306,  307,

      307,  308,  308,  309,  309,  310,  310,  311,  311,  312,
      312,  313,  313,  314,  314,    0,  305,  315,  315,  316,
      316,  317,  317,  318,  318,  319,  319,  321,  321,  322,
      322,  323,  323,  324,  324,  325,  325,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "snocone.l"
#line 2 "snocone.l"
/*
 * snocone.l — Snocone Flex lexer (GOAL-SNOCONE-LANG-SPACE LS-3)
 *
 * DESIGN:
 *   Space envelops the operator.  Pattern {W}OP{W} matches the operator
 *   together with its surrounding whitespace.  Whitespace alone (between
 *   two atoms with no operator between them) lexes as T_CONCAT.  Unary
 *   versions of dual-role operators arrive bare (no leading space) and
 *   are returned as T_UN_*.  This matches the snobol4.l lexer pattern
 *   exactly (lines 235-315 of snobol4.l).
 *
 *   The CONCAT decision is therefore not a previous-token state machine
 *   — it falls out of the rule patterns themselves.  This is the
 *   elegant SNOBOL4-Flex approach: longest-match selects the right rule,
 *   and the token stream is unambiguous by construction.
 *
 * NAMING: token names match snobol4.tab.h conventions (T_IDENT, T_INT,
 *   T_REAL, T_STR, T_FUNCTION, T_KEYWORD, T_CONCAT, T_ADDITION, etc.)
 *   to keep one4all "same names everywhere for any concept equivalence"
 *   (RULES.md / Lon's session-#9 directive).
 *
 * Andrew's .sc operator set, minus &&, ||, %.  Plus C-style control
 * flow keywords (if/else/while/do/until/for/switch/case/default/break/
 * continue/goto/function/return/freturn/nreturn/struct).
 *
 * Commit identity: LCherryholmes / lcherryh@yahoo.com  (RULES.md)
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "snocone_lex2.h"

static int   sc_lineno = 1;
static char  sc_strbuf[65536];
static int   sc_strpos;

static void emit_simple(LexerState *st, int kind, const char *text);
static void emit_str(LexerState *st, const char *s);
static int  classify_keyword(const char *s);
static void count_newlines(const char *s);

/* push token with default text=yytext */
#define EMIT(kind) emit_simple(yyextra, (kind), yytext)
#define EMIT_NL(kind) do { count_newlines(yytext); emit_simple(yyextra, (kind), yytext); } while(0)

#line 953 "snocone.lex.c"
#define YY_NO_INPUT 1

#line 956 "snocone.lex.c"

#define INITIAL 0
#define BODY_START 1
#define BODY 2
#define STR1 3
#define STR2 4
#define BLOCK_COMMENT 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#define YY_EXTRA_TYPE LexerState *

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    }; /* end struct yyguts_t */

static int yy_init_globals ( yyscan_t yyscanner );

int yylex_init (yyscan_t* scanner);

int yylex_init_extra ( YY_EXTRA_TYPE user_defined, yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( yyscan_t yyscanner );

int yyget_debug ( yyscan_t yyscanner );

void yyset_debug ( int debug_flag , yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra ( yyscan_t yyscanner );

void yyset_extra ( YY_EXTRA_TYPE user_defined , yyscan_t yyscanner );

FILE *yyget_in ( yyscan_t yyscanner );

void yyset_in  ( FILE * _in_str , yyscan_t yyscanner );

FILE *yyget_out ( yyscan_t yyscanner );

void yyset_out  ( FILE * _out_str , yyscan_t yyscanner );

			int yyget_leng ( yyscan_t yyscanner );

char *yyget_text ( yyscan_t yyscanner );

int yyget_lineno ( yyscan_t yyscanner );

void yyset_lineno ( int _line_number , yyscan_t yyscanner );

int yyget_column  ( yyscan_t yyscanner );

void yyset_column ( int _column_no , yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( yyscan_t yyscanner );
#else
extern int yywrap ( yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int , yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * , yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( yyscan_t yyscanner );
#else
static int input ( yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (yyscan_t yyscanner);

#define YY_DECL int yylex (yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
		}

		yy_load_buffer_state( yyscanner );
		}

	{
#line 65 "snocone.l"


#line 68 "snocone.l"
  /* INITIAL: jump straight into BODY (no card-format dispatch in Snocone —
   * Snocone uses C-style blocks, semicolons, and free-form layout). */
#line 1223 "snocone.lex.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 321 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 738 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 70 "snocone.l"
{ yyless(0); BEGIN(BODY); }
	YY_BREAK
/* ========================================================== */
/* BODY: statement body                                       */
/* ========================================================== */
/* Comments are pure whitespace (transparent for CONCAT). */
case 2:
YY_RULE_SETUP
#line 77 "snocone.l"
{ /* line comment — fall through to next ws */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 78 "snocone.l"
{ BEGIN(BLOCK_COMMENT); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 80 "snocone.l"
{ BEGIN(BODY); }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 81 "snocone.l"
{ sc_lineno++; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 82 "snocone.l"
{ /* absorbed */ }
	YY_BREAK
/* String literals — STR1 single-quote, STR2 double-quote.
   * SNOBOL4 strings: no backslash escapes; '' inside '...' is one '.   */
case 7:
YY_RULE_SETUP
#line 86 "snocone.l"
{ sc_strpos = 0; BEGIN(STR1); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 87 "snocone.l"
{ sc_strpos = 0; BEGIN(STR2); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 89 "snocone.l"
{ sc_strbuf[sc_strpos++] = '\''; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 90 "snocone.l"
{ sc_strbuf[sc_strpos] = '\0';
                              BEGIN(BODY);
                              emit_str(yyextra, sc_strbuf); }
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 93 "snocone.l"
{ sc_strbuf[sc_strpos++] = '\n'; sc_lineno++; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 94 "snocone.l"
{ sc_strbuf[sc_strpos++] = yytext[0]; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 96 "snocone.l"
{ sc_strbuf[sc_strpos++] = '"'; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 97 "snocone.l"
{ sc_strbuf[sc_strpos] = '\0';
                              BEGIN(BODY);
                              emit_str(yyextra, sc_strbuf); }
	YY_BREAK
case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
#line 100 "snocone.l"
{ sc_strbuf[sc_strpos++] = '\n'; sc_lineno++; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 101 "snocone.l"
{ sc_strbuf[sc_strpos++] = yytext[0]; }
	YY_BREAK
/* &IDENT as one token (no space between & and ident) — like SNOBOL4 */
case 17:
YY_RULE_SETUP
#line 104 "snocone.l"
{ emit_simple(yyextra, T_KEYWORD, yytext + 1); }
	YY_BREAK
/* T_CONCAT: pure whitespace between two atoms — emit if previous token
   * was atom-class.  We inhibit emission immediately after openers / before
   * closers / at end-of-statement using the prev-token-class check inside
   * emit_simple.  In the {W}OP{W} pattern below, the operator's surrounding
   * space is consumed *with* the operator, so plain {W} only matches when
   * no operator follows — that's where CONCAT belongs. */
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 112 "snocone.l"
{ count_newlines(yytext);
                              emit_simple(yyextra, T_CONCAT, ""); }
	YY_BREAK
/* ========================================================== */
/* Binary operators: {W} OP {W}                              */
/* The mandatory whitespace on at least one side distinguishes */
/* binary use from unary.  Where unary form is the ONLY        */
/* meaningful interpretation we drop the W-envelope.           */
/* ========================================================== */
/* SPITBOL/Snocone priority-0 assign — = with required surrounding space */
case 19:
/* rule 19 can match eol */
YY_RULE_SETUP
#line 123 "snocone.l"
{ EMIT_NL(T_ASSIGNMENT); }
	YY_BREAK
/* = at end-of-line / no trailing space — still T_ASSIGNMENT (DYN-63 mirror) */
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 125 "snocone.l"
{ EMIT_NL(T_ASSIGNMENT); }
	YY_BREAK
/* Pattern match — same shape */
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 128 "snocone.l"
{ EMIT_NL(T_MATCH); }
	YY_BREAK
/* Alternation */
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 131 "snocone.l"
{ EMIT_NL(T_ALTERNATION); }
	YY_BREAK
/* String comparison — multi-character, must come BEFORE the */
/* single-char rules to win the longest-match contest.       */
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
#line 135 "snocone.l"
{ EMIT_NL(T_LEQ); }
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 136 "snocone.l"
{ EMIT_NL(T_LNE); }
	YY_BREAK
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 137 "snocone.l"
{ EMIT_NL(T_LLE); }
	YY_BREAK
case 26:
/* rule 26 can match eol */
YY_RULE_SETUP
#line 138 "snocone.l"
{ EMIT_NL(T_LGE); }
	YY_BREAK
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
#line 139 "snocone.l"
{ EMIT_NL(T_LLT); }
	YY_BREAK
case 28:
/* rule 28 can match eol */
YY_RULE_SETUP
#line 140 "snocone.l"
{ EMIT_NL(T_LGT); }
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 141 "snocone.l"
{ EMIT_NL(T_DIFFER); }
	YY_BREAK
case 30:
/* rule 30 can match eol */
YY_RULE_SETUP
#line 142 "snocone.l"
{ EMIT_NL(T_IDENT_OP); }
	YY_BREAK
/* Numeric comparison (Andrew's .sc 6-op set) */
case 31:
/* rule 31 can match eol */
YY_RULE_SETUP
#line 145 "snocone.l"
{ EMIT_NL(T_EQ); }
	YY_BREAK
case 32:
/* rule 32 can match eol */
YY_RULE_SETUP
#line 146 "snocone.l"
{ EMIT_NL(T_NE); }
	YY_BREAK
case 33:
/* rule 33 can match eol */
YY_RULE_SETUP
#line 147 "snocone.l"
{ EMIT_NL(T_LE); }
	YY_BREAK
case 34:
/* rule 34 can match eol */
YY_RULE_SETUP
#line 148 "snocone.l"
{ EMIT_NL(T_GE); }
	YY_BREAK
case 35:
/* rule 35 can match eol */
YY_RULE_SETUP
#line 149 "snocone.l"
{ EMIT_NL(T_LT); }
	YY_BREAK
case 36:
/* rule 36 can match eol */
YY_RULE_SETUP
#line 150 "snocone.l"
{ EMIT_NL(T_GT); }
	YY_BREAK
/* Compound-assignments — adopted in today's lexer; LS-2 will decide
   * whether the grammar accepts these.  The lexer keeps them. */
case 37:
/* rule 37 can match eol */
YY_RULE_SETUP
#line 154 "snocone.l"
{ EMIT_NL(T_PLUS_ASSIGN); }
	YY_BREAK
case 38:
/* rule 38 can match eol */
YY_RULE_SETUP
#line 155 "snocone.l"
{ EMIT_NL(T_MINUS_ASSIGN); }
	YY_BREAK
case 39:
/* rule 39 can match eol */
YY_RULE_SETUP
#line 156 "snocone.l"
{ EMIT_NL(T_STAR_ASSIGN); }
	YY_BREAK
case 40:
/* rule 40 can match eol */
YY_RULE_SETUP
#line 157 "snocone.l"
{ EMIT_NL(T_SLASH_ASSIGN); }
	YY_BREAK
case 41:
/* rule 41 can match eol */
YY_RULE_SETUP
#line 158 "snocone.l"
{ EMIT_NL(T_CARET_ASSIGN); }
	YY_BREAK
/* Exponentiation synonyms: ^, **, !  (pri 11 right-assoc) */
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
#line 161 "snocone.l"
{ EMIT_NL(T_EXPONENTIATION); }
	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 162 "snocone.l"
{ EMIT_NL(T_EXPONENTIATION); }
	YY_BREAK
case 44:
/* rule 44 can match eol */
YY_RULE_SETUP
#line 163 "snocone.l"
{ EMIT_NL(T_EXPONENTIATION); }
	YY_BREAK
/* Arithmetic */
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 166 "snocone.l"
{ EMIT_NL(T_ADDITION); }
	YY_BREAK
case 46:
/* rule 46 can match eol */
YY_RULE_SETUP
#line 167 "snocone.l"
{ EMIT_NL(T_SUBTRACTION); }
	YY_BREAK
case 47:
/* rule 47 can match eol */
YY_RULE_SETUP
#line 168 "snocone.l"
{ EMIT_NL(T_MULTIPLICATION); }
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 169 "snocone.l"
{ EMIT_NL(T_DIVISION); }
	YY_BREAK
/* Indirection (binary $ — immediate assign in pattern context) */
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 172 "snocone.l"
{ EMIT_NL(T_IMMEDIATE_ASSIGN); }
	YY_BREAK
/* Name-of (binary . — conditional assign in pattern context) */
case 50:
/* rule 50 can match eol */
YY_RULE_SETUP
#line 174 "snocone.l"
{ EMIT_NL(T_COND_ASSIGN); }
	YY_BREAK
/* OPSYN slot operators (binary forms — Andrew's & % @ # ~) */
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
#line 177 "snocone.l"
{ EMIT_NL(T_AMPERSAND); }
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 178 "snocone.l"
{ EMIT_NL(T_AT_SIGN); }
	YY_BREAK
case 53:
/* rule 53 can match eol */
YY_RULE_SETUP
#line 179 "snocone.l"
{ EMIT_NL(T_PERCENT); }
	YY_BREAK
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 180 "snocone.l"
{ EMIT_NL(T_TILDE); }
	YY_BREAK
case 55:
/* rule 55 can match eol */
YY_RULE_SETUP
#line 181 "snocone.l"
{ EMIT_NL(T_POUND); }
	YY_BREAK
/* ========================================================== */
/* Structural punctuation                                    */
/* ========================================================== */
/* ( absorbs trailing gray (matches snobol4.l line 281).
   * IMPORTANT: ( with NO leading whitespace and a preceding identifier
   * is the call-form — handled by the T_FUNCTION rule below via trailing
   * context.  This rule fires for sub-expression parens.            */
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 191 "snocone.l"
{ EMIT_NL(T_LPAREN); }
	YY_BREAK
case 57:
/* rule 57 can match eol */
YY_RULE_SETUP
#line 192 "snocone.l"
{ EMIT_NL(T_RPAREN); }
	YY_BREAK
case 58:
/* rule 58 can match eol */
YY_RULE_SETUP
#line 193 "snocone.l"
{ EMIT_NL(T_LBRACK); }
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 194 "snocone.l"
{ EMIT_NL(T_RBRACK); }
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 195 "snocone.l"
{ EMIT_NL(T_COMMA); }
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 196 "snocone.l"
{ EMIT_NL(T_SEMICOLON); }
	YY_BREAK
/* Block braces (Snocone-only) — gray on outside */
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 199 "snocone.l"
{ EMIT_NL(T_LBRACE); }
	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 200 "snocone.l"
{ EMIT_NL(T_RBRACE); }
	YY_BREAK
/* Colon: label suffix.  Andrew's .sc uses `name : clause` (label) and
   * `case value :` (switch case).  This is a bare colon — the multi-char
   * comparison rules above (`:==:` etc.) win longest-match. */
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 205 "snocone.l"
{ EMIT_NL(T_COLON); }
	YY_BREAK
/* ========================================================== */
/* Atoms — arrive bare (preceding T_CONCAT or W{OP} consumed   */
/* the leading whitespace already)                            */
/* ========================================================== */
/* T_FUNCTION: identifier immediately followed by '(' (no space).
   * Same trick as snobol4.l line 290.  The '(' stays in the input
   * stream — the BODY '(' rule consumes it next as T_LPAREN.  Grammar
   * sees: T_FUNCTION T_LPAREN args T_RPAREN. */
case 65:
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
yyg->yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 216 "snocone.l"
{ emit_simple(yyextra, T_FUNCTION, yytext); }
	YY_BREAK
/* T_IDENT or keyword */
case 66:
YY_RULE_SETUP
#line 219 "snocone.l"
{
                              int kind = classify_keyword(yytext);
                              emit_simple(yyextra, kind, yytext);
                            }
	YY_BREAK
/* Numbers — REAL forms before INT (longest-match) */
case 67:
YY_RULE_SETUP
#line 225 "snocone.l"
{ EMIT(T_REAL); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 226 "snocone.l"
{ EMIT(T_REAL); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 227 "snocone.l"
{ EMIT(T_REAL); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 228 "snocone.l"
{ EMIT(T_INT); }
	YY_BREAK
/* ========================================================== */
/* Unary operators — bare (no leading W).  The grammar has    */
/* T_UN_* productions for each.                               */
/* ========================================================== */
case 71:
YY_RULE_SETUP
#line 235 "snocone.l"
{ EMIT(T_EXPONENTIATION); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 236 "snocone.l"
{ EMIT(T_EXPONENTIATION); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 237 "snocone.l"
{ EMIT(T_EXPONENTIATION); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 238 "snocone.l"
{ EMIT(T_UN_PLUS); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 239 "snocone.l"
{ EMIT(T_UN_MINUS); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 240 "snocone.l"
{ EMIT(T_UN_ASTERISK); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 241 "snocone.l"
{ EMIT(T_UN_SLASH); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 242 "snocone.l"
{ EMIT(T_UN_PERCENT); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 243 "snocone.l"
{ EMIT(T_UN_AT_SIGN); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 244 "snocone.l"
{ EMIT(T_UN_TILDE); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 245 "snocone.l"
{ EMIT(T_UN_DOLLAR_SIGN); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 246 "snocone.l"
{ EMIT(T_UN_PERIOD); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 247 "snocone.l"
{ EMIT(T_UN_POUND); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 248 "snocone.l"
{ EMIT(T_UN_VERTICAL_BAR); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 249 "snocone.l"
{ EMIT(T_UN_EQUAL); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 250 "snocone.l"
{ EMIT(T_UN_QUESTION_MARK); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 251 "snocone.l"
{ EMIT(T_UN_AMPERSAND); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 253 "snocone.l"
{
    /* Unrecognised character */
    emit_simple(yyextra, T_UNKNOWN, yytext);
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(BODY_START):
case YY_STATE_EOF(BODY):
case YY_STATE_EOF(STR1):
case YY_STATE_EOF(STR2):
case YY_STATE_EOF(BLOCK_COMMENT):
#line 258 "snocone.l"
{
    emit_simple(yyextra, T_EOF, "");
    yyterminate();
}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 263 "snocone.l"
ECHO;
	YY_BREAK
#line 1860 "snocone.lex.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap( yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  , yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size , yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 321 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	char *yy_cp = yyg->yy_c_buf_p;

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 321 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 320);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr);
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin , yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file , yyscanner);
	yy_load_buffer_state( yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file , yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf , yyscanner );

	yyfree( (void *) b , yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer( b , yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER , yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b , yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) , yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n , yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n , yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void yyset_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* Accessor methods for yylval and yylloc */

/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */
int yylex_init(yyscan_t* ptr_yy_globals)
{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */
int yylex_init_extra( YY_EXTRA_TYPE yy_user_defined, yyscan_t* ptr_yy_globals )
{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    yyset_extra (yy_user_defined, *ptr_yy_globals);

    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = NULL;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = NULL;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER , yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack , yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree( yyg->yy_start_stack , yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 263 "snocone.l"


/* ========================================================== */
/* Keyword table — case-sensitive (RULES.md)                  */
/* ========================================================== */

typedef struct { const char *word; int kind; } KwEntry;
static const KwEntry KW_TABLE[] = {
    /* Control flow */
    { "if",       T_KW_IF       },
    { "else",     T_KW_ELSE     },
    { "while",    T_KW_WHILE    },
    { "do",       T_KW_DO       },
    { "until",    T_KW_UNTIL    },
    { "for",      T_KW_FOR      },
    { "switch",   T_KW_SWITCH   },
    { "case",     T_KW_CASE     },
    { "default",  T_KW_DEFAULT  },
    { "break",    T_KW_BREAK    },
    { "continue", T_KW_CONTINUE },
    { "goto",     T_KW_GOTO     },
    /* Function / return */
    { "function", T_KW_FUNCTION },   /* RENAMED from procedure (session #7) */
    { "return",   T_KW_RETURN   },
    { "freturn",  T_KW_FRETURN  },
    { "nreturn",  T_KW_NRETURN  },
    /* Data */
    { "struct",   T_KW_STRUCT   },
    { NULL,       T_IDENT       }
};

static int classify_keyword(const char *s) {
    for (const KwEntry *e = KW_TABLE; e->word; e++)
        if (strcmp(s, e->word) == 0) return e->kind;
    return T_IDENT;
}

/* ========================================================== */
/* Token-buffer accumulation                                  */
/* ========================================================== */

static void emit_simple(LexerState *st, int kind, const char *text) {
    /* CONCAT suppression: never emit two CONCATs in a row, never emit
     * CONCAT at the start of the token stream, never emit CONCAT
     * immediately after an opener or operator (its purpose is to
     * separate two value-yielding atoms only). */
    if (kind == T_CONCAT) {
        if (st->buf->count == 0) return;
        int last = st->buf->tokens[st->buf->count - 1].kind;
        if (last == T_CONCAT) return;
        /* If the previous token is non-value (operator, opener, separator),
         * the whitespace is just trivia.  Only emit CONCAT after value-
         * yielding tokens. */
        if (!sc_kind_is_value(last)) return;
    }

    /* If we were about to emit a value-yielding token but the previous
     * token was also a value-yielding token AND no CONCAT has been
     * emitted between them, the source had no whitespace between the
     * two atoms.  In SNOBOL4 lexing the {W} envelope already inserts
     * the CONCAT (because at least one space is required between two
     * atoms with no operator between them).  In Snocone we inherit
     * the same property: this branch is dead in correct programs. */

    if (st->buf->count >= st->buf->capacity) {
        st->buf->capacity = st->buf->capacity ? st->buf->capacity * 2 : 64;
        st->buf->tokens   = realloc(st->buf->tokens,
                                    st->buf->capacity * sizeof(ScToken2));
    }
    ScToken2 *t = &st->buf->tokens[st->buf->count++];
    t->kind = kind;
    t->text = strdup(text);
    t->line = sc_lineno;
}

static void emit_str(LexerState *st, const char *s) {
    emit_simple(st, T_STR, s);
}

static void count_newlines(const char *s) {
    for (const char *p = s; *p; p++)
        if (*p == '\n') sc_lineno++;
}

/* sc_kind_is_value: does this token kind end an expression / could a
 * CONCAT validly follow it? */
int sc_kind_is_value(int kind) {
    switch (kind) {
    case T_IDENT:
    case T_FUNCTION:
    case T_INT:
    case T_REAL:
    case T_STR:
    case T_KEYWORD:
    case T_RPAREN:
    case T_RBRACK:
        return 1;
    default:
        return 0;
    }
}

/* ========================================================== */
/* Public API                                                 */
/* ========================================================== */

ScTokenBuf snocone_lex2(const char *source) {
    LexerState st;
    memset(&st, 0, sizeof(st));

    ScTokenBuf buf;
    memset(&buf, 0, sizeof(buf));
    st.buf = &buf;

    sc_lineno = 1;

    yyscan_t scanner;
    sc_lex_init_extra(&st, &scanner);
    YY_BUFFER_STATE ybuf = sc__scan_string(source, scanner);
    sc_lex(scanner);
    sc__delete_buffer(ybuf, scanner);
    sc_lex_destroy(scanner);

    return buf;
}

void sc_token_buf_free(ScTokenBuf *buf) {
    for (int i = 0; i < buf->count; i++) free(buf->tokens[i].text);
    free(buf->tokens);
    buf->tokens = NULL;
    buf->count = 0;
    buf->capacity = 0;
}

const char *sc2_kind_name(int kind) {
    switch (kind) {
    case T_INT:                  return "T_INT";
    case T_REAL:                 return "T_REAL";
    case T_STR:                  return "T_STR";
    case T_IDENT:                return "T_IDENT";
    case T_FUNCTION:             return "T_FUNCTION";
    case T_KEYWORD:              return "T_KEYWORD";
    case T_CONCAT:               return "T_CONCAT";
    case T_ASSIGNMENT:           return "T_ASSIGNMENT";
    case T_MATCH:                return "T_MATCH";
    case T_ALTERNATION:          return "T_ALTERNATION";
    case T_ADDITION:             return "T_ADDITION";
    case T_SUBTRACTION:          return "T_SUBTRACTION";
    case T_MULTIPLICATION:       return "T_MULTIPLICATION";
    case T_DIVISION:             return "T_DIVISION";
    case T_EXPONENTIATION:       return "T_EXPONENTIATION";
    case T_IMMEDIATE_ASSIGN:     return "T_IMMEDIATE_ASSIGN";
    case T_COND_ASSIGN:          return "T_COND_ASSIGN";
    case T_AMPERSAND:            return "T_AMPERSAND";
    case T_AT_SIGN:              return "T_AT_SIGN";
    case T_POUND:                return "T_POUND";
    case T_PERCENT:              return "T_PERCENT";
    case T_TILDE:                return "T_TILDE";
    case T_EQ:                   return "T_EQ";
    case T_NE:                   return "T_NE";
    case T_LT:                   return "T_LT";
    case T_GT:                   return "T_GT";
    case T_LE:                   return "T_LE";
    case T_GE:                   return "T_GE";
    case T_LEQ:                  return "T_LEQ";
    case T_LNE:                  return "T_LNE";
    case T_LLT:                  return "T_LLT";
    case T_LGT:                  return "T_LGT";
    case T_LLE:                  return "T_LLE";
    case T_LGE:                  return "T_LGE";
    case T_IDENT_OP:             return "T_IDENT_OP";
    case T_DIFFER:               return "T_DIFFER";
    case T_PLUS_ASSIGN:          return "T_PLUS_ASSIGN";
    case T_MINUS_ASSIGN:         return "T_MINUS_ASSIGN";
    case T_STAR_ASSIGN:          return "T_STAR_ASSIGN";
    case T_SLASH_ASSIGN:         return "T_SLASH_ASSIGN";
    case T_CARET_ASSIGN:         return "T_CARET_ASSIGN";
    case T_UN_PLUS:              return "T_UN_PLUS";
    case T_UN_MINUS:             return "T_UN_MINUS";
    case T_UN_ASTERISK:          return "T_UN_ASTERISK";
    case T_UN_SLASH:             return "T_UN_SLASH";
    case T_UN_PERCENT:           return "T_UN_PERCENT";
    case T_UN_AT_SIGN:           return "T_UN_AT_SIGN";
    case T_UN_TILDE:             return "T_UN_TILDE";
    case T_UN_DOLLAR_SIGN:       return "T_UN_DOLLAR_SIGN";
    case T_UN_PERIOD:            return "T_UN_PERIOD";
    case T_UN_POUND:             return "T_UN_POUND";
    case T_UN_VERTICAL_BAR:      return "T_UN_VERTICAL_BAR";
    case T_UN_EQUAL:             return "T_UN_EQUAL";
    case T_UN_QUESTION_MARK:     return "T_UN_QUESTION_MARK";
    case T_UN_AMPERSAND:         return "T_UN_AMPERSAND";
    case T_LPAREN:               return "T_LPAREN";
    case T_RPAREN:               return "T_RPAREN";
    case T_LBRACE:               return "T_LBRACE";
    case T_RBRACE:               return "T_RBRACE";
    case T_LBRACK:               return "T_LBRACK";
    case T_RBRACK:               return "T_RBRACK";
    case T_COMMA:                return "T_COMMA";
    case T_SEMICOLON:            return "T_SEMICOLON";
    case T_COLON:                return "T_COLON";
    case T_KW_IF:                return "T_KW_IF";
    case T_KW_ELSE:              return "T_KW_ELSE";
    case T_KW_WHILE:             return "T_KW_WHILE";
    case T_KW_DO:                return "T_KW_DO";
    case T_KW_UNTIL:             return "T_KW_UNTIL";
    case T_KW_FOR:               return "T_KW_FOR";
    case T_KW_SWITCH:            return "T_KW_SWITCH";
    case T_KW_CASE:              return "T_KW_CASE";
    case T_KW_DEFAULT:           return "T_KW_DEFAULT";
    case T_KW_BREAK:             return "T_KW_BREAK";
    case T_KW_CONTINUE:          return "T_KW_CONTINUE";
    case T_KW_GOTO:              return "T_KW_GOTO";
    case T_KW_FUNCTION:          return "T_KW_FUNCTION";
    case T_KW_RETURN:            return "T_KW_RETURN";
    case T_KW_FRETURN:           return "T_KW_FRETURN";
    case T_KW_NRETURN:           return "T_KW_NRETURN";
    case T_KW_STRUCT:            return "T_KW_STRUCT";
    case T_EOF:                  return "T_EOF";
    case T_UNKNOWN:              return "T_UNKNOWN";
    default:                     return "T_???";
    }
}

