/*
 * test_snocone_parse_i.c — GOAL-SNOCONE-LANG-SPACE LS-4.i acceptance test
 *
 * Sub-step LS-4.i.1: `goto LABEL;` and `LABEL:` prefix.
 *
 * Lowering shapes:
 *
 *   goto NAME ;        ->   :(NAME)        (bare goto-uncond stmt; no subject)
 *
 *   NAME : stmt        ->   NAME           (label pad: subject=NULL,
 *                          <stmts of stmt>  go=NULL, label=NAME)
 *                          + the inner stmt's stmts immediately following.
 *                          Per SNOBOL4 semantics, a label on a label-only
 *                          pad chains to the next non-empty stmt — so
 *                          jumping to NAME lands on the inner stmt.
 *
 * Label declarations and goto targets are user names verbatim.  No
 * synthetic prefixing or mangling — `top` stays `top`.  Synthetic
 * labels generated by control-flow lowering (`_Lend_NNNN` etc.) carry
 * a leading underscore that user labels cannot, so collisions are
 * impossible by construction.
 *
 * Side-channel test — the LS-4.i parser is not yet wired into scrip's
 * production driver path (that happens at LS-4.j).
 *
 * AUTHORS: Lon Jones Cherryholmes · Claude Sonnet
 * Commit identity: LCherryholmes / lcherryh@yahoo.com  (RULES.md)
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define IR_DEFINE_NAMES
#include "scrip_cc.h"

Program *snocone_parse_program(const char *src, const char *filename);

/* ---- harness ---- */
static int g_pass = 0, g_fail = 0;

#define ASSERT(cond, fmt, ...) do { \
    if (cond) { g_pass++; } \
    else { fprintf(stderr, "FAIL %s:%d: " fmt "\n", __func__, __LINE__, ##__VA_ARGS__); g_fail++; } \
} while(0)

/* Walk the linked-list and collect a STMT_t* array (caller must free). */
static STMT_t **collect_stmts(Program *prog, int *out_n) {
    int n = 0;
    for (STMT_t *s = prog->head; s; s = s->next) n++;
    STMT_t **arr = calloc(n, sizeof *arr);
    int i = 0;
    for (STMT_t *s = prog->head; s; s = s->next) arr[i++] = s;
    *out_n = n;
    return arr;
}

/* True if stmt is a bare label-only landing pad (no subject, no goto). */
static int is_label_pad(STMT_t *s) { return s->label && !s->subject && !s->go; }
/* True if stmt is a goto-only statement (no subject). */
static int is_goto_uncond(STMT_t *s) { return s->go && s->go->uncond && !s->subject; }
/* True if stmt is a bare expression (subject, no goto). */
static int is_bare_expr(STMT_t *s) { return s->subject && !s->go; }
/* True if stmt is an assignment (subject + replacement, has_eq). */
static int is_assignment(STMT_t *s) { return s->subject && s->replacement && s->has_eq; }

/* =========================================================================
 * Test 1 — bare goto
 *   goto top;
 *   Expected:
 *     stmt[0] :(top)             (goto-uncond, no subject)
 * ========================================================================= */
static void test_goto_bare(void) {
    Program *prog = snocone_parse_program("goto top;", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(n == 1, "expected 1 stmt, got %d", n);
    if (n >= 1) {
        ASSERT(is_goto_uncond(stmts[0]), "stmt[0] should be goto-uncond");
        ASSERT(stmts[0]->go && stmts[0]->go->uncond &&
               strcmp(stmts[0]->go->uncond, "top") == 0,
               "goto target should be \"top\", got %s",
               stmts[0]->go && stmts[0]->go->uncond ? stmts[0]->go->uncond : "(null)");
        ASSERT(stmts[0]->subject == NULL, "goto stmt should have no subject");
        ASSERT(stmts[0]->label == NULL, "goto stmt should have no label");
    }
    free(stmts);
}

/* =========================================================================
 * Test 2 — goto inside a sequence
 *   x = 1; goto fin; y = 2;
 *   Expected:
 *     stmt[0] x = 1
 *     stmt[1] :(fin)
 *     stmt[2] y = 2
 * ========================================================================= */
static void test_goto_in_sequence(void) {
    Program *prog = snocone_parse_program("x = 1; goto fin; y = 2;", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(n == 3, "expected 3 stmts, got %d", n);
    if (n >= 1) ASSERT(is_assignment(stmts[0]), "stmt[0] should be assignment");
    if (n >= 2) {
        ASSERT(is_goto_uncond(stmts[1]), "stmt[1] should be goto");
        ASSERT(stmts[1]->go && stmts[1]->go->uncond &&
               strcmp(stmts[1]->go->uncond, "fin") == 0,
               "goto target should be \"fin\"");
    }
    if (n >= 3) ASSERT(is_assignment(stmts[2]), "stmt[2] should be assignment");
    free(stmts);
}

/* =========================================================================
 * Test 3 — bare label before assignment
 *   top: x = 1;
 *   Expected:
 *     stmt[0] top                (label pad — chains to stmt[1] semantically)
 *     stmt[1] x = 1
 * ========================================================================= */
static void test_label_before_assign(void) {
    Program *prog = snocone_parse_program("top: x = 1;", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(n == 2, "expected 2 stmts, got %d", n);
    if (n >= 1) {
        ASSERT(is_label_pad(stmts[0]), "stmt[0] should be label pad");
        ASSERT(stmts[0]->label && strcmp(stmts[0]->label, "top") == 0,
               "stmt[0] label should be \"top\", got %s",
               stmts[0]->label ? stmts[0]->label : "(null)");
    }
    if (n >= 2) ASSERT(is_assignment(stmts[1]), "stmt[1] should be assignment");
    free(stmts);
}

/* =========================================================================
 * Test 4 — label + goto round-trip
 *   top: x = 1; goto top;
 *   Expected:
 *     stmt[0] top
 *     stmt[1] x = 1
 *     stmt[2] :(top)
 * ========================================================================= */
static void test_label_and_goto_loop(void) {
    Program *prog = snocone_parse_program("top: x = 1; goto top;", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(n == 3, "expected 3 stmts, got %d", n);
    if (n >= 1) {
        ASSERT(is_label_pad(stmts[0]), "stmt[0] should be label pad");
        ASSERT(stmts[0]->label && strcmp(stmts[0]->label, "top") == 0,
               "stmt[0] label should be \"top\"");
    }
    if (n >= 2) ASSERT(is_assignment(stmts[1]), "stmt[1] should be assignment");
    if (n >= 3) {
        ASSERT(is_goto_uncond(stmts[2]), "stmt[2] should be goto-uncond");
        ASSERT(stmts[2]->go && stmts[2]->go->uncond &&
               strcmp(stmts[2]->go->uncond, "top") == 0,
               "goto target should be \"top\"");
    }
    free(stmts);
}

/* =========================================================================
 * Test 5 — label before block
 *   header: { x = 1; y = 2; }
 *   Expected:
 *     stmt[0] header              (label pad)
 *     stmt[1] x = 1
 *     stmt[2] y = 2
 * ========================================================================= */
static void test_label_before_block(void) {
    Program *prog = snocone_parse_program("header: { x = 1; y = 2; }", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(n == 3, "expected 3 stmts, got %d", n);
    if (n >= 1) {
        ASSERT(is_label_pad(stmts[0]), "stmt[0] should be label pad");
        ASSERT(stmts[0]->label && strcmp(stmts[0]->label, "header") == 0,
               "stmt[0] label should be \"header\"");
    }
    free(stmts);
}

/* =========================================================================
 * Test 6 — label before if-stmt
 *   skip_it: if (DIFFER(x)) { y = 1; }
 *   Expected:
 *     stmt[0] skip_it             (user label pad)
 *     stmt[1] DIFFER(x)  :F(_Lend_0001)
 *     stmt[2] y = 1
 *     stmt[3] _Lend_0001          (synthetic if-end label)
 * ========================================================================= */
static void test_label_before_if(void) {
    Program *prog = snocone_parse_program(
        "skip_it: if (DIFFER(x)) { y = 1; }", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(n == 4, "expected 4 stmts, got %d", n);
    if (n >= 1) {
        ASSERT(is_label_pad(stmts[0]), "stmt[0] should be label pad");
        ASSERT(stmts[0]->label && strcmp(stmts[0]->label, "skip_it") == 0,
               "stmt[0] label should be \"skip_it\"");
    }
    if (n >= 2) {
        /* cond stmt with onfailure target */
        ASSERT(stmts[1]->subject != NULL, "stmt[1] should have subject");
        ASSERT(stmts[1]->go && stmts[1]->go->onfailure,
               "stmt[1] should have onfailure goto");
    }
    free(stmts);
}

/* =========================================================================
 * Test 7 — label before while-stmt (interaction with synthetic _Ltop)
 *   user_top: while (DIFFER(x)) { x = x; }
 *   Expected:
 *     stmt[0] user_top                  (USER label pad — first)
 *     stmt[1] _Ltop_0001                (synthetic loop top — second)
 *     stmt[2] DIFFER(x)  :F(_Lend_0002)
 *     stmt[3] x = x
 *     stmt[4] :(_Ltop_0001)             (back-edge to synthetic top)
 *     stmt[5] _Lend_0002                (synthetic loop end pad)
 *
 *   The user label `user_top` sits BEFORE the synthetic `_Ltop_NNNN`
 *   pad — so `goto user_top;` from elsewhere lands on the
 *   synthetic top via SNOBOL4's label-chaining (label-only pads
 *   chain forward to the next non-empty stmt, which is the
 *   cond stmt — same effective entry as the synthetic top).
 * ========================================================================= */
static void test_label_before_while(void) {
    Program *prog = snocone_parse_program(
        "user_top: while (DIFFER(x)) { x = x; }", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(n == 6, "expected 6 stmts, got %d", n);
    if (n >= 1) {
        ASSERT(is_label_pad(stmts[0]), "stmt[0] should be user label pad");
        ASSERT(stmts[0]->label && strcmp(stmts[0]->label, "user_top") == 0,
               "stmt[0] label should be \"user_top\", got %s",
               stmts[0]->label ? stmts[0]->label : "(null)");
    }
    if (n >= 2) {
        ASSERT(is_label_pad(stmts[1]), "stmt[1] should be synthetic _Ltop pad");
        ASSERT(stmts[1]->label && strncmp(stmts[1]->label, "_Ltop_", 6) == 0,
               "stmt[1] label should start with _Ltop_, got %s",
               stmts[1]->label ? stmts[1]->label : "(null)");
    }
    free(stmts);
}

/* =========================================================================
 * Test 8 — multiple goto targets / no collision
 *   x = 1; goto a; goto b; goto c;
 *   Expected: stmt[0..3] subject/goto sequence with three distinct uncond targets.
 * ========================================================================= */
static void test_multiple_goto_targets(void) {
    Program *prog = snocone_parse_program("x = 1; goto a; goto b; goto c;", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(n == 4, "expected 4 stmts, got %d", n);
    if (n >= 4) {
        ASSERT(is_assignment(stmts[0]), "stmt[0] should be assignment");
        ASSERT(is_goto_uncond(stmts[1]) && stmts[1]->go &&
               strcmp(stmts[1]->go->uncond, "a") == 0, "stmt[1] should be :(a)");
        ASSERT(is_goto_uncond(stmts[2]) && stmts[2]->go &&
               strcmp(stmts[2]->go->uncond, "b") == 0, "stmt[2] should be :(b)");
        ASSERT(is_goto_uncond(stmts[3]) && stmts[3]->go &&
               strcmp(stmts[3]->go->uncond, "c") == 0, "stmt[3] should be :(c)");
    }
    free(stmts);
}

/* =========================================================================
 * Test 9 — multiple labels at consecutive positions
 *   first: second: x = 1;
 *   Expected:
 *     stmt[0] first
 *     stmt[1] second
 *     stmt[2] x = 1
 *
 *   Stacked labels via the recursive `label_decl matched_stmt` rule.
 *   In SPITBOL terms both labels chain forward to the assignment.
 * ========================================================================= */
static void test_stacked_labels(void) {
    Program *prog = snocone_parse_program("first: second: x = 1;", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(n == 3, "expected 3 stmts, got %d", n);
    if (n >= 1) {
        ASSERT(is_label_pad(stmts[0]), "stmt[0] should be label pad");
        ASSERT(stmts[0]->label && strcmp(stmts[0]->label, "first") == 0,
               "stmt[0] label should be \"first\"");
    }
    if (n >= 2) {
        ASSERT(is_label_pad(stmts[1]), "stmt[1] should be label pad");
        ASSERT(stmts[1]->label && strcmp(stmts[1]->label, "second") == 0,
               "stmt[1] label should be \"second\"");
    }
    if (n >= 3) ASSERT(is_assignment(stmts[2]), "stmt[2] should be assignment");
    free(stmts);
}

/* =========================================================================
 * Test 10 — label before empty stmt
 *   pad: ;
 *   Expected: just stmt[0] = label pad (the trailing `;` is empty stmt,
 *             which appends nothing).
 * ========================================================================= */
static void test_label_before_empty_stmt(void) {
    Program *prog = snocone_parse_program("pad: ;", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(n == 1, "expected 1 stmt, got %d", n);
    if (n >= 1) {
        ASSERT(is_label_pad(stmts[0]), "stmt[0] should be label pad");
        ASSERT(stmts[0]->label && strcmp(stmts[0]->label, "pad") == 0,
               "stmt[0] label should be \"pad\"");
    }
    free(stmts);
}

/* =========================================================================
 * Test 11 — label inside a function body
 *   function F() { again: x = 1; goto again; }
 *   Expected:
 *     stmt[0] DEFINE('F()')
 *     stmt[1] :(F_end)
 *     stmt[2] F           (entry-point label)
 *     stmt[3] again       (user label)
 *     stmt[4] x = 1
 *     stmt[5] :(again)
 *     stmt[6] F_end
 * ========================================================================= */
static void test_label_inside_function(void) {
    Program *prog = snocone_parse_program(
        "function F() { again: x = 1; goto again; }", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(n == 7, "expected 7 stmts, got %d", n);
    if (n >= 1) ASSERT(is_bare_expr(stmts[0]), "stmt[0] should be DEFINE bare-expr");
    if (n >= 2) ASSERT(is_goto_uncond(stmts[1]), "stmt[1] should be skip-goto");
    if (n >= 3) {
        ASSERT(is_label_pad(stmts[2]), "stmt[2] should be entry label F");
        ASSERT(stmts[2]->label && strcmp(stmts[2]->label, "F") == 0,
               "stmt[2] label should be \"F\"");
    }
    if (n >= 4) {
        ASSERT(is_label_pad(stmts[3]), "stmt[3] should be user label again");
        ASSERT(stmts[3]->label && strcmp(stmts[3]->label, "again") == 0,
               "stmt[3] label should be \"again\"");
    }
    if (n >= 5) ASSERT(is_assignment(stmts[4]), "stmt[4] should be assignment");
    if (n >= 6) {
        ASSERT(is_goto_uncond(stmts[5]), "stmt[5] should be goto");
        ASSERT(stmts[5]->go && stmts[5]->go->uncond &&
               strcmp(stmts[5]->go->uncond, "again") == 0,
               "stmt[5] target should be \"again\"");
    }
    if (n >= 7) {
        ASSERT(is_label_pad(stmts[6]), "stmt[6] should be F_end pad");
        ASSERT(stmts[6]->label && strcmp(stmts[6]->label, "F_end") == 0,
               "stmt[6] label should be \"F_end\"");
    }
    free(stmts);
}

/* =========================================================================
 * Test 12 — pre-existing stmts before label preserved
 *   x = 0; user: y = 1;
 *   Expected:
 *     stmt[0] x = 0
 *     stmt[1] user            (label pad)
 *     stmt[2] y = 1
 * ========================================================================= */
static void test_label_with_preceding_stmts(void) {
    Program *prog = snocone_parse_program("x = 0; user: y = 1;", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(n == 3, "expected 3 stmts, got %d", n);
    if (n >= 1) ASSERT(is_assignment(stmts[0]), "stmt[0] should be x=0");
    if (n >= 2) {
        ASSERT(is_label_pad(stmts[1]), "stmt[1] should be label pad");
        ASSERT(stmts[1]->label && strcmp(stmts[1]->label, "user") == 0,
               "stmt[1] label should be \"user\"");
    }
    if (n >= 3) ASSERT(is_assignment(stmts[2]), "stmt[2] should be y=1");
    free(stmts);
}

/* =========================================================================
 * Test 13 — labels with whitespace variations
 *   "name :stmt" and "name: stmt" and "name :stmt" and "name :   stmt"
 *   should all produce the same shape — colon is just a token, not
 *   whitespace-sensitive at this level.
 * ========================================================================= */
static void test_label_whitespace_variants(void) {
    const char *variants[] = {
        "L: x = 1;",
        "L : x = 1;",
        "L  :  x = 1;",
        "L :x = 1;",
    };
    for (size_t i = 0; i < sizeof variants / sizeof variants[0]; i++) {
        Program *prog = snocone_parse_program(variants[i], "test");
        ASSERT(prog != NULL, "variant %zu parse failed: %s", i, variants[i]);
        if (!prog) continue;
        int n; STMT_t **stmts = collect_stmts(prog, &n);
        ASSERT(n == 2, "variant %zu expected 2 stmts, got %d", i, n);
        if (n >= 1) {
            ASSERT(is_label_pad(stmts[0]), "variant %zu stmt[0] should be label pad", i);
            ASSERT(stmts[0]->label && strcmp(stmts[0]->label, "L") == 0,
                   "variant %zu stmt[0] label should be \"L\"", i);
        }
        free(stmts);
    }
}

/* =========================================================================
 * Test 14 — goto whitespace variations
 * ========================================================================= */
static void test_goto_whitespace_variants(void) {
    const char *variants[] = {
        "goto top;",
        "goto  top ;",
        "goto\ttop;",
    };
    for (size_t i = 0; i < sizeof variants / sizeof variants[0]; i++) {
        Program *prog = snocone_parse_program(variants[i], "test");
        ASSERT(prog != NULL, "variant %zu parse failed: %s", i, variants[i]);
        if (!prog) continue;
        int n; STMT_t **stmts = collect_stmts(prog, &n);
        ASSERT(n == 1, "variant %zu expected 1 stmt, got %d", i, n);
        if (n >= 1) {
            ASSERT(is_goto_uncond(stmts[0]), "variant %zu stmt[0] should be goto", i);
            ASSERT(stmts[0]->go && stmts[0]->go->uncond &&
                   strcmp(stmts[0]->go->uncond, "top") == 0,
                   "variant %zu target should be \"top\"", i);
        }
        free(stmts);
    }
}

/* =========================================================================
 * Test 15 — label inside while body
 *   while (DIFFER(x)) { inner: x = x; }
 *   Inner label should appear inside the loop body, after the loop's
 *   cond stmt, before the body assignment, before the back-edge goto.
 * ========================================================================= */
static void test_label_inside_while(void) {
    Program *prog = snocone_parse_program(
        "while (DIFFER(x)) { inner: x = x; }", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    /*  stmt[0] _Ltop pad
     *  stmt[1] cond :F(_Lend)
     *  stmt[2] inner pad           (user label)
     *  stmt[3] x = x
     *  stmt[4] :(_Ltop)
     *  stmt[5] _Lend pad
     */
    ASSERT(n == 6, "expected 6 stmts, got %d", n);
    if (n >= 3) {
        ASSERT(is_label_pad(stmts[2]), "stmt[2] should be user label \"inner\"");
        ASSERT(stmts[2]->label && strcmp(stmts[2]->label, "inner") == 0,
               "stmt[2] label should be \"inner\", got %s",
               stmts[2]->label ? stmts[2]->label : "(null)");
    }
    free(stmts);
}

int main(void) {
    test_goto_bare();
    test_goto_in_sequence();
    test_label_before_assign();
    test_label_and_goto_loop();
    test_label_before_block();
    test_label_before_if();
    test_label_before_while();
    test_multiple_goto_targets();
    test_stacked_labels();
    test_label_before_empty_stmt();
    test_label_inside_function();
    test_label_with_preceding_stmts();
    test_label_whitespace_variants();
    test_goto_whitespace_variants();
    test_label_inside_while();
    printf("=== Results: %d passed, %d failed ===\n", g_pass, g_fail);
    return g_fail == 0 ? 0 : 1;
}
