; generated by sno2c -asm-body — link with snobol4_asm_harness.o
; assemble: nasm -f elf64 body.s -o body.o
; link:     gcc -no-pie -o prog body.o snobol4_asm_harness.o

    global root_alpha, root_beta
    extern cursor, subject_data, subject_len_val
    extern match_success, match_fail
    extern outer_cursor
    global cap_order, cap_order_count


section .data


; per-variable capture name strings
cap_name_A                db  65, 0
cap_name_B                db  66, 0
cap_name_C                db  67, 0

; cap_order[] = { name*, buf*, len* } ... null-terminated
cap_order:
    dq  cap_name_A           , cap_A_buf, cap_A_len
    dq  cap_name_B           , cap_B_buf, cap_B_len
    dq  cap_name_C           , cap_C_buf, cap_C_len
    dq  0, 0, 0
cap_order_count  dq  3

section .bss

pat_PAT_ret_gamma        resq 1
pat_PAT_ret_omega        resq 1
dol_entry_A              resq 1
len4_saved               resq 1
dol_entry_B              resq 1
len6_saved               resq 1
dol_entry_C              resq 1
len8_saved               resq 1
cap_A_buf                resb 256
cap_A_len                resq 1
cap_B_buf                resb 256
cap_B_len                resq 1
cap_C_buf                resb 256
cap_C_len                resq 1

section .text


; REF(PAT) α=root_alpha
root_alpha:
    lea     rax, [rel nref0_gamma]
    mov     [pat_PAT_ret_gamma], rax
    lea     rax, [rel nref0_omega]
    mov     [pat_PAT_ret_omega], rax
    jmp     pat_PAT_alpha

; REF(PAT) β=root_beta
root_beta:
    lea     rax, [rel nref0_gamma]
    mov     [pat_PAT_ret_gamma], rax
    lea     rax, [rel nref0_omega]
    mov     [pat_PAT_ret_omega], rax
    jmp     pat_PAT_beta

nref0_gamma:
    jmp     match_success
nref0_omega:
    jmp     match_fail

; ============ Named pattern: PAT ============
; pat_PAT_alpha (α entry)

; SEQ α=pat_PAT_alpha
pat_PAT_alpha:
    jmp     seq_l1_alpha
pat_PAT_beta:
    jmp     seq_r1_beta

; SEQ α=seq_l1_alpha
seq_l1_alpha:
    jmp     seq_l2_alpha
seq_l1_beta:
    jmp     seq_r2_beta

; DOL(A $  A)  α=seq_l2_alpha
seq_l2_alpha:
    mov     rax, [cursor]
    mov     [dol_entry_A], rax
    jmp     dol3_child_alpha
seq_l2_beta:
    jmp     dol3_child_beta

; LEN(2)  α=dol3_child_alpha
dol3_child_alpha:
    mov     rax, [cursor]
    mov     [len4_saved], rax
    add     rax, 2
    cmp     rax, [subject_len_val]
    jg      dol3_omega
    mov     [cursor], rax
    jmp     dol3_gamma

; LEN β=dol3_child_beta
dol3_child_beta:
    mov     rax, [len4_saved]
    mov     [cursor], rax
    jmp     dol3_omega

; DOL γ — capture span into cap_A_buf
dol3_gamma:
    mov     rax, [cursor]
    mov     rbx, [dol_entry_A]
    sub     rax, rbx
    mov     [cap_A_len], rax
    lea     rsi, [rel subject_data]
    add     rsi, rbx
    lea     rdi, [rel cap_A_buf]
    mov     rcx, rax
    rep     movsb
    jmp     seq_r2_alpha

; DOL ω — child failed, no capture
dol3_omega:
    jmp     patdef_PAT_omega

; DOL(B $  B)  α=seq_r2_alpha
seq_r2_alpha:
    mov     rax, [cursor]
    mov     [dol_entry_B], rax
    jmp     dol5_child_alpha
seq_r2_beta:
    jmp     dol5_child_beta

; LEN(2)  α=dol5_child_alpha
dol5_child_alpha:
    mov     rax, [cursor]
    mov     [len6_saved], rax
    add     rax, 2
    cmp     rax, [subject_len_val]
    jg      dol5_omega
    mov     [cursor], rax
    jmp     dol5_gamma

; LEN β=dol5_child_beta
dol5_child_beta:
    mov     rax, [len6_saved]
    mov     [cursor], rax
    jmp     dol5_omega

; DOL γ — capture span into cap_B_buf
dol5_gamma:
    mov     rax, [cursor]
    mov     rbx, [dol_entry_B]
    sub     rax, rbx
    mov     [cap_B_len], rax
    lea     rsi, [rel subject_data]
    add     rsi, rbx
    lea     rdi, [rel cap_B_buf]
    mov     rcx, rax
    rep     movsb
    jmp     seq_r1_alpha

; DOL ω — child failed, no capture
dol5_omega:
    jmp     seq_l2_beta

; DOL(C $  C)  α=seq_r1_alpha
seq_r1_alpha:
    mov     rax, [cursor]
    mov     [dol_entry_C], rax
    jmp     dol7_child_alpha
seq_r1_beta:
    jmp     dol7_child_beta

; LEN(2)  α=dol7_child_alpha
dol7_child_alpha:
    mov     rax, [cursor]
    mov     [len8_saved], rax
    add     rax, 2
    cmp     rax, [subject_len_val]
    jg      dol7_omega
    mov     [cursor], rax
    jmp     dol7_gamma

; LEN β=dol7_child_beta
dol7_child_beta:
    mov     rax, [len8_saved]
    mov     [cursor], rax
    jmp     dol7_omega

; DOL γ — capture span into cap_C_buf
dol7_gamma:
    mov     rax, [cursor]
    mov     rbx, [dol_entry_C]
    sub     rax, rbx
    mov     [cap_C_len], rax
    lea     rsi, [rel subject_data]
    add     rsi, rbx
    lea     rdi, [rel cap_C_buf]
    mov     rcx, rax
    rep     movsb
    jmp     patdef_PAT_gamma

; DOL ω — child failed, no capture
dol7_omega:
    jmp     seq_l1_beta

patdef_PAT_gamma:
    jmp     [pat_PAT_ret_gamma]
patdef_PAT_omega:
    jmp     [pat_PAT_ret_omega]
