; generated by sno2c -asm-body — link with snobol4_asm_harness.o
; assemble: nasm -f elf64 body.s -o body.o
; link:     gcc -no-pie -o prog body.o snobol4_asm_harness.o

    global root_alpha, root_beta
    extern cursor, subject_data, subject_len_val
    extern match_success, match_fail
    extern outer_cursor
    global cap_order, cap_order_count


section .data

lit_str_1            db 104, 101, 108, 108, 111

; per-variable capture name strings
cap_name_V                db  86, 0

; cap_order[] = { name*, buf*, len* } ... null-terminated
cap_order:
    dq  cap_name_V           , cap_V_buf, cap_V_len
    dq  0, 0, 0
cap_order_count  dq  1

section .bss

pat_PAT_ret_gamma        resq 1
pat_PAT_ret_omega        resq 1
dol_entry_V              resq 1
pat_PAT_alpha_saved      resq 1
cap_V_buf                resb 256
cap_V_len                resq 1

section .text


; DOL(V $  V)  α=root_alpha
root_alpha:
    mov     rax, [cursor]
    mov     [dol_entry_V], rax
    jmp     dol0_child_alpha
root_beta:
    jmp     dol0_child_beta

; REF(PAT) α=dol0_child_alpha
dol0_child_alpha:
    lea     rax, [rel nref1_gamma]
    mov     [pat_PAT_ret_gamma], rax
    lea     rax, [rel nref1_omega]
    mov     [pat_PAT_ret_omega], rax
    jmp     pat_PAT_alpha

; REF(PAT) β=dol0_child_beta
dol0_child_beta:
    lea     rax, [rel nref1_gamma]
    mov     [pat_PAT_ret_gamma], rax
    lea     rax, [rel nref1_omega]
    mov     [pat_PAT_ret_omega], rax
    jmp     pat_PAT_beta

nref1_gamma:
    jmp     dol0_gamma
nref1_omega:
    jmp     dol0_omega

; DOL γ — capture span into cap_V_buf
dol0_gamma:
    mov     rax, [cursor]
    mov     rbx, [dol_entry_V]
    sub     rax, rbx
    mov     [cap_V_len], rax
    lea     rsi, [rel subject_data]
    add     rsi, rbx
    lea     rdi, [rel cap_V_buf]
    mov     rcx, rax
    rep     movsb
    jmp     match_success

; DOL ω — child failed, no capture
dol0_omega:
    jmp     match_fail

; ============ Named pattern: PAT ============
; pat_PAT_alpha (α entry)

; LIT("hello")  α=pat_PAT_alpha
pat_PAT_alpha:
    mov     rax, [cursor]
    add     rax, 5
    cmp     rax, [subject_len_val]
    jg      patdef_PAT_omega
    lea     rsi, [rel subject_data]
    mov     rcx, [cursor]
    add     rsi, rcx
    lea     rdi, [rel lit_str_1]
    mov     rcx, 5
    repe    cmpsb
    jne     patdef_PAT_omega
    mov     rax, [cursor]
    mov     [pat_PAT_alpha_saved], rax
    add     rax, 5
    mov     [cursor], rax
    jmp     patdef_PAT_gamma

; LIT β=pat_PAT_beta
pat_PAT_beta:
    mov     rax, [pat_PAT_alpha_saved]
    mov     [cursor], rax
    jmp     patdef_PAT_omega

patdef_PAT_gamma:
    jmp     [pat_PAT_ret_gamma]
patdef_PAT_omega:
    jmp     [pat_PAT_ret_omega]
